*---------------------------------------------------------------------------------------------------
* SNOBOL4 requires a stubbed version of FENCE()
*---------------------------------------------------------------------------------------------------
               IsSnobol4()                                                          :F(FENCEEnd)
               DEFINE('FENCE(FENCE)')                                               :(FENCEEnd)
FENCE                                                                               :(RETURN)
FENCEEnd
