{
1 "Addition left operand is not numeric"
2 "Addition right operand is not numeric"
3 "Addition caused integer overflow"
4 "Affirmation operand is not numeric"
5 "Alternation right operand is not pattern"
6 "Alternation left operand is not pattern"
7 "Compilation error encountered during execution"
8 "Concatenation left operand is not a string or pattern"
9 "Concatenation right operand is not a string or pattern"
10 "Negation operand is not numeric"
11 "Negation caused integer overflow"
12 "Division left operand is not numeric"
13 "Division right operand is not numeric"
14 "Division caused integer overflow"
15 "Exponentiation right operand is not numeric"
16 "Exponentiation left operand is not numeric"
17 "Exponentiation caused integer overflow"
18 "Exponentiation result is undefined"
20 "Goto evaluation failure"
21 "Function called by name returned a value"
22 "Undefined function called"
23 "Goto operand is not a natural variable"
24 "Goto operand in direct goto is not code"
25 "Immediate assignment left operand is not pattern"
26 "Multiplication left operand is not numeric"
27 "Multiplication right operand is not numeric"
28 "Multiplication caused integer overflow"
29 "Undefined operator referenced"
30 "Pattern assignment left operand is not pattern"
31 "Pattern replacement right operand is not a string"
32 "Subtraction left operand is not numeric"
33 "Subtraction right operand is not numeric"
34 "Subtraction caused integer overflow"
35 "Unexpected failure in -NOFAIL mode"
36 "Goto ABORT with no preceding error"
37 "Goto CONTINUE with no preceding error"
38 "Goto undefined label"
39 "External function argument is not a string"
40 "External function argument is not integer"
41 "FIELD function argument is wrong datatype"
42 "Attempt to change value of protected variable"
43 "ANY evaluated argument is not a string"
44 "BREAK evaluated argument is not a string"
45 "BREAKX evaluated argument is not a string"
46 "Expression does not evaluate to pattern"
47 "LEN evaluated argument is not integer"
48 "LEN evaluated argument is negative or too large"
49 "NOTANY evaluated argument is not a string"
50 "POS evaluated argument is not integer"
51 "POS evaluated argument is negative or too large"
52 "RPOS evaluated argument is not integer"
53 "RPOS evaluated argument is negative or too large"
54 "RTAB evaluated argument is not integer"
55 "RTAB evaluated argument is negative or too large"
56 "SPAN evaluated argument is not a string"
57 "TAB evaluated argument is not integer"
58 "TAB evaluated argument is negative or too large"
59 "ANY argument is not a string or expression"
60 "APPLY first arg is not natural variable name"
61 "ARBNO argument is not pattern"
62 "ARG second argument is not integer"
63 "ARG first argument is not program function name"
64 "ARRAY first argument is not integer or string"
65 "ARRAY first argument lower bound is not integer"
66 "ARRAY first argument upper bound is not integer"
67 "ARRAY dimension is zero,negative or out of range"
68 "ARRAY size exceeds maximum permitted"
69 "BREAK argument is not a string or expression"
70 "BREAKX argument is not a string or expression"
71 "CLEAR argument is not a string"
72 "CLEAR argument has null variable name"
73 "COLLECT argument is not integer"
74 "CONVERT second argument is not a string"
75 "DATA argument is not a string"
76 "DATA argument is null"
77 "DATA argument is missing a left paren"
78 "DATA argument has null datatype name"
79 "DATA argument is missing a right paren"
80 "DATA argument has null field name"
81 "DEFINE first argument is not a string"
82 "DEFINE first argument is null"
83 "DEFINE first argument is missing a left paren"
84 "DEFINE first argument has null function name"
85 "Null arg name or missing ) in DEFINE first arg."
86 "DEFINE function entry point is not defined label"
87 "DETACH argument is not appropriate name"
88 "DUMP argument is not integer"
89 "DUMP argument is negative or too large"
90 "DUPL second argument is not integer"
91 "DUPL first argument is not a string or pattern"
92 "EJECT argument is not a suitable name"
93 "EJECT file does not exist"
94 "EJECT file does not permit page eject"
95 "EJECT caused non-recoverable output error"
274 "Appendices"
96 "ENDFILE argument is not a suitable name"
97 "ENDFILE argument is null"
98 "ENDFILE file does not exist"
99 "ENDFILE file does not permit endfile"
100 "ENDFILE caused non-recoverable output error"
101 "EQ first argument is not numeric"
102 "EQ second argument is not numeric"
103 "EVAL argument is not expression"
104 "EXIT first argument is not suitable integer or string"
105 "EXIT action not available in this implementation"
106 "EXIT action caused irrecoverable error"
107 "FIELD second argument is not integer"
108 "FIELD first argument is not datatype name"
109 "GE first argument is not numeric"
110 "GE second argument is not numeric"
111 "GT first argument is not numeric"
112 "GT second argument is not numeric"
113 "INPUT third argument is not a string"
114 "Inappropriate second argument for INPUT"
115 "Inappropriate first argument for INPUT"
116 "Inappropriate file specification for INPUT"
117 "INPUT file cannot be read"
118 "LE first argument is not numeric"
119 "LE second argument is not numeric"
120 "LEN argument is not integer or expression"
121 "LEN argument is negative or too large"
122 "LEQ first argument is not a string"
123 "LEQ second argument is not a string"
124 "LGE first argument is not a string"
125 "LGE second argument is not a string"
126 "LGT first argument is not a string"
127 "LGT second argument is not a string"
128 "LLE first argument is not a string"
129 "LLE second argument is not a string"
130 "LLT first argument is not a string"
131 "LLT second argument is not a string"
132 "LNE first argument is not a string"
133 "LNE second argument is not a string"
134 "LOCAL second argument is not integer"
135 "LOCAL first arg is not a program function name"
136 "LOAD second argument is not a string"
137 "LOAD first argument is not a string"
138 "LOAD first argument is null"
139 "LOAD first argument is missing a left paren"
140 "LOAD first argument has null function name"
141 "LOAD first argument is missing a right paren"
142 "LOAD function does not exist"
143 "LOAD function caused input error during load"
144 "LPAD third argument not a string"
145 "LPAD second argument is not integer"
146 "LPAD first argument is not a string"
147 "LT first argument is not numeric"
148 "LT second argument is not numeric"
149 "NE first argument is not numeric"
150 "NE second argument is not numeric"
151 "NOTANY argument is not a string or expression"
152 "OPSYN third argument is not integer"
153 "OPSYN third argument is negative or too large"
154 "OPSYN second arg is not natural variable name"
155 "OPSYN first arg is not natural variable name"
156 "OPSYN first arg is not correct operator name"
157 "OUTPUT third argument is not a string"
158 "Inappropriate second argument for OUTPUT"
159 "Inappropriate first argument for OUTPUT"
160 "Inappropriate file specification for OUTPUT"
161 "OUTPUT file cannot be written to"
162 "POS argument is not integer or expression"
163 "POS argument is negative or too large"
164 "PROTOTYPE argument is not valid object"
165 "REMDR second argument is not numeric"
166 "REMDR first argument is not integer"
167 "REMDR caused integer overflow"
168 "REPLACE third argument is not a string"
169 "REPLACE second argument is not a string"
170 "REPLACE first argument is not a string"
171 "Null or unequally long 2nd, 3rd args to REPLACE"
172 "REWIND argument is not a suitable name"
173 "REWIND argument is null"
174 "REWIND file does not exist"
175 "REWIND file does not permit rewind"
176 "REWIND caused non-recoverable error"
177 "REVERSE argument is not a string"
178 "RPAD third argument is not a string"
179 "RPAD second argument is not integer"
180 "RPAD first argument is not a string"
181 "RTAB argument is not integer or expression"
182 "RTAB argument is negative or too large"
183 "TAB argument is not integer or expression"
184 "TAB argument is negative or too large"
185 "RPOS argument is not integer or expression"
186 "RPOS argument is negative or too large"
187 "SETEXIT argument is not label name or null"
188 "SPAN argument is not a string or expression"
189 "SIZE argument is not a string"
190 "STOPTR first argument is not appropriate name"
191 "STOPTR second argument is not trace type"
192 "SUBSTR third argument is not integer"
193 "SUBSTR second argument is not integer"
276 "Appendices"
194 "SUBSTR first argument is not a string"
195 "TABLE argument is not integer"
196 "TABLE argument is out of range"
197 "TRACE fourth arg is not function name or null"
198 "TRACE first argument is not appropriate name"
199 "TRACE second argument is not trace type"
200 "TRIM argument is not a string"
201 "UNLOAD argument is not natural variable name"
202 "Input from file caused non-recoverable error"
203 "Input file record has incorrect format"
204 "Memory overflow"
205 "String length exceeds value of MAXLNGTH keyword"
206 "Output caused file overflow"
207 "Output caused non-recoverable error"
208 "Keyword value assigned is not integer"
209 "Keyword in assignment is protected"
210 "Keyword value assigned is negative or too large"
211 "Value assigned to keyword ERRTEXT not a string"
212 "Syntax error: Value used where name is required"
213 "Syntax error: Statement is too complicated."
214 "Bad label or misplaced continuation line"
215 "Syntax error: Undefined or erroneous entry label"
216 "Syntax error: Missing END line"
217 "Syntax error: Duplicate label"
218 "Syntax error: Duplicated goto field"
219 "Syntax error: Empty goto field"
220 "Syntax error: Missing operator"
221 "Syntax error: Missing operand"
222 "Syntax error: Invalid use of left bracket"
223 "Syntax error: Invalid use of comma"
224 "Syntax error: Unbalanced right parenthesis"
225 "Syntax error: Unbalanced right bracket"
226 "Syntax error: Missing right paren"
227 "Syntax error: Right paren missing from goto"
228 "Syntax error: Right bracket missing from goto"
229 "Syntax error: Missing right array bracket"
230 "Syntax error: Illegal character"
231 "Syntax error: Invalid numeric item"
232 "Syntax error: Unmatched string quote"
233 "Syntax error: Invalid use of operator"
234 "Syntax error: Goto field incorrect"
235 "Subscripted operand is not table or array"
236 "Array referenced with wrong number of subscripts"
237 "Table referenced with more than one subscript"
238 "Array subscript is not integer"
239 "Indirection operand is not name"
240 "Pattern match right operand is not pattern"
241 "Pattern match left operand is not a string"
242 "Function return from level zero"
243 "Function result in NRETURN is not name"
244 "Statement count exceeds value of STLIMIT keyword"
246 "Stack overflow"
247 "Invalid control statement"
248 "Attempted redefinition of system function"
249 "Expression evaluated by name returned value"
250 "Insufficient memory to complete dump"
251 "Keyword operand is not name of defined keyword"
252 "Error on printing to interactive channel"
254 "Erroneous argument for HOST"
255 "Error during execution of HOST"
256 "SORT/RSORT 1st arg not suitable ARRAY or TABLE"
257 "Erroneous 2nd arg in SORT/RSORT of vector"
258 "SORT/RSORT 2nd arg out of range or non-integer"
259 "FENCE argument is not pattern"
260 "Conversion array size exceeds maximum permitted"
261 "Addition caused real overflow"
262 "Division caused real overflow"
263 "Multiplication caused real overflow"
264 "Subtraction caused real overflow"
265 "External function argument is not real"
266 "Exponentiation caused real overflow"
268 "Inconsistent value assigned to keyword PROFILE"
270 "BACKSPACE argument is not a suitable name"
271 "BACKSPACE file does not exist"
272 "BACKSPACE file does not permit backspace"
273 "BACKSPACE caused non-recoverable error"
281 "Char argument not integer"
282 "Char argument not in range"
284 "Excessively nested INCLUDE files"
285 "INCLUDE file cannot be opened"
286 "Function call to undefined entry label"
287 "Value assigned to keyword MAXLNGTH is too small"
288 "EXIT second argument is not a string"
291 "SET first argument is not a suitable name"
292 "SET first argument is null"
293 "Inappropriate second argument to SET"
294 "Inappropriate third argument to SET"
295 "SET file does not exist"
296 "SET file does not permit setting file pointer"
297 "SET caused non-recoverable I/O error"
298 "External function argument is not file"
299 "Internal logic error: Unexpected PPM branch"
301 "ATAN argument not numeric"
302 "CHOP argument not numeric"
303 "COS argument not numeric"
304 "EXP argument not numeric"
305 "EXP produced real overflow"
306 "LN argument not numeric"
278 "Appendices"
307 "LN produced real overflow"
308 "SIN argument not numeric"
309 "TAN argument not numeric"
310 "TAN produced real overflow"
311 "Exponentiation of negative base to non-integral power"
312 "REMDR caused real overflow"
313 "SQRT argument not numeric"
314 "SQRT argument negative"
315 "LN argument negative"
320 "User interrupt"
321 "Goto SCONTINUE with no preceding error"
326 "Calling external function – bad argument type"
327 "Calling external function – not found"
328 "LOAD function – insufficient memory"
329 "Requested MAXLNGTH too large"
}