            '.'                                 =  '.'
            '@'                                 =  '@'
            ','                                 =  ','
            '('                                 =  '('
            ')'                                 =  ')'
            ';'                                 =  ';'
            NUMBER                              =  ''
            NEGNUMBER                           =  ''
            POSNUMBER                           =  ''
            DECIMAL                             =  ''
            POSDECIMAL                          =  ''
            NEGDECIMAL                          =  ''
            ENUMBER                             =  ''
            SYMBOL                              =  ''
            UND_SYMBOL                          =  ''
            STRING                              =  ''
            $'_SQ_STRING_'                      =  ''
            BLOCK_TEXT                          =  ''
            LONG_STRING_BEG                     =  ''
            LONG_STRING_END                     =  ''
            LONG_STRING_MID                     =  ''
            $'_CONDITION_'                      =  ''
            $'_QUERY_BODY_'                     =  ''
            $'_EOT_'                            =  ''
            $'_ADD'                             =  ''
            $'_ACTION'                          =  ''
            $'_AFTER'                           =  ''
            $'_ALIAS'                           =  ''
            $'_ALL'                             =  ''
            $'_ALTER'                           =  ''
            $'_ANY'                             =  ''
            $'_AS'                              =  ''
            $'_ASC'                             =  ''
            $'_ASCII'                           =  ''
            $'_AUDIT'                           =  ''
            $'_AUTHID'                          =  ''
            $'_BEFORE'                          =  ''
            $'_BIT'                             =  ''
            $'_BLOBSPACE'                       =  ''
            $'_BNODEGROUP'                      =  ''
            $'_BUFFERPOOL'                      =  ''
            $'_BY'                              =  ''
            $'_CAPTURE'                         =  ''
            $'_CASCADE'                         =  ''
            $'_CCSID'                           =  ''
            $'_CHANGED'                         =  ''
            $'_CHANGES'                         =  ''
            $'_CHAR'                            =  ''
            $'_CHECK'                           =  ''
            $'_CHUNK'                           =  ''
            $'_CLOSE'                           =  ''
            $'_CLUSTER'                         =  ''
            $'_COLCOMMENT'                      =  ''
            $'_COLLABEL'                        =  ''
            $'_COLUMN'                          =  ''
            $'_COLUMNS'                         =  ''
            $'_COMMENT'                         =  ''
            $'_COMPRESS'                        =  ''
            $'_CONTAINER'                       =  ''
            $'_CREATE'                          =  ''
            $'_CURRENT'                         =  ''
            $'_DATA'                            =  ''
            $'_DATABASE'                        =  ''
            $'_DATABASE_DEVICE'                 =  ''
            $'_DATABASE_LINK'                   =  ''
            $'_DATE'                            =  ''
            $'_DB2'                             =  ''
            $'_DBSPACE'                         =  ''
            $'_DECIMAL'                         =  ''
            $'_DEFAULT'                         =  ''
            $'_DEFAULTVALUE'                    =  ''
            $'_DEFLT'                           =  ''
            $'_DELETE'                          =  ''
            $'_DESC'                            =  ''
            $'_DIRECTORY'                       =  ''
            $'_DISTINCT_TYPE'                   =  ''
            $'_DROP'                            =  ''
            $'_DROPRESTRICT'                    =  ''
            $'_EBCDIC'                          =  ''
            $'_DSETPASS'                        =  ''
            $'_EDITPROC'                        =  ''
            $'_ERASE'                           =  ''
            $'_EVENT_MONITOR'                   =  ''
            $'_EXTENT'                          =  ''
            $'_FIELDPROC'                       =  ''
            $'_FILEGROUP'                       =  ''
            $'_FILE'                            =  ''
            $'_FLOAT'                           =  ''
            $'_FOR'                             =  ''
            $'_FOREIGN'                         =  ''
            $'_FOREIGN_KEY'                     =  ''
            $'_FRAGMENT'                        =  ''
            $'_FREEPAGE'                        =  ''
            $'_FROM'                            =  ''
            $'_FUNCTION'                        =  ''
            $'_G'                               =  ''
            $'_GLOBAL'                          =  ''
            $'_GPCACHE'                         =  ''
            $'_GRAPHIC'                         =  ''
            $'_GROUP'                           =  ''
            $'_HAVING'                          =  ''
            $'_INDEX'                           =  ''
            $'_INFORMIX'                        =  ''
            $'_INTEGER'                         =  ''
            $'_K'                               =  ''
            $'_KEY'                             =  ''
            $'_KEYCOLUMNS'                      =  ''
            $'_LABEL'                           =  ''
            $'_LOB_OBJECT'                      =  ''
            $'_LOB_PARTITION'                   =  ''
            $'_LOB_SUBPARTITION'                =  ''
            $'_LOCAL'                           =  ''
            $'_LOCATION'                        =  ''
            $'_LOCKMAX'                         =  ''
            $'_LOCKSIZE'                        =  ''
            $'_LOGICAL_COMMONKEY'               =  ''
            $'_LOGICAL_FOREIGNKEY'              =  ''
            $'_LOGICAL_PRIMARYKEY'              =  ''
            $'_LOGIN'                           =  ''
            $'_LONG'                            =  ''
            $'_M'                               =  ''
            $'_MEMBER'                          =  ''
            $'_MIGRATE'                         =  ''
            $'_HTMLREPORT'                      =  ''
            $'_MIGRATEDEPSONLY'                 =  ''
            $'_MIXED'                           =  ''
            $'_MODIFY'                          =  ''
            $'_MOVE'                            =  ''
            $'_N'                               =  ''
            $'_NAME'                            =  ''
            $'_NO'                              =  ''
            $'_NOCOLCOMMENT'                    =  ''
            $'_NOCOLLABEL'                      =  ''
            $'_NOCOLUMNS'                       =  ''
            $'_NOCOMMENT'                       =  ''
            $'_NODE'                            =  ''
            $'_NODEGROUP'                       =  ''
            $'_NODSETPASS'                      =  ''
            $'_NOEDITPROC'                      =  ''
            $'_NOLABEL'                         =  ''
            $'_NONE'                            =  ''
            $'_NOPRIMARYKEY'                    =  ''
            $'_NOSETPASS'                       =  ''
            $'_NOT'                             =  ''
            $'_NOTNULL'                         =  ''
            $'_NOVALIDPROC'                     =  ''
            $'_NOVCATPASS'                      =  ''
            $'_NULL'                            =  ''
            $'_NUMPARTS'                        =  ''
            $'_OBID'                            =  ''
            $'_ON'                              =  ''
            $'_OPTION'                          =  ''
            $'_ORACLE'                          =  ''
            $'_OWNER'                           =  ''
            $'_PACKAGE'                         =  ''
            $'_PACKAGE_BODY'                    =  ''
            $'_PAGE'                            =  ''
            $'_PARAMETER'                       =  ''
            $'_PART'                            =  ''
            $'_PARTS'                           =  ''
            $'_PARTITION'                       =  ''
            $'_PIECESIZE'                       =  ''
            $'_PCTFREE'                         =  ''
            $'_POSITION'                        =  ''
            $'_PRIMARYKEY'                      =  ''
            $'_PRIMARY_KEY'                     =  ''
            $'_PRIQTY'                          =  ''
            $'_PROCEDURE'                       =  ''
            $'_PROFILE'                         =  ''
            $'_QUALIFIED'                       =  ''
            $'_QUALIFIER'                       =  ''
            $'_QUOTA'                           =  ''
            $'_READ'                            =  ''
            $'_REBUILD'                         =  ''
            $'_RECOMPILE'                       =  ''
            $'_REFCOLUMNS'                      =  ''
            $'_REFERENCETB'                     =  ''
            $'_REFRESH_GROUP'                   =  ''
            $'_RELEASE'                         =  ''
            $'_RESOURCE'                        =  ''
            $'_RESTRICT'                        =  ''
            $'_RETURN'                          =  ''
            $'_ROLE'                            =  ''
            $'_ROLLBACK_SEGMENT'                =  ''
            $'_ROSHARE'                         =  ''
            $'_ROW'                             =  ''
            $'_RULE'                            =  ''
            $'_SBCS'                            =  ''
            $'_SCHEMA'                          =  ''
            $'_SECQTY'                          =  ''
            $'_SEGMENT'                         =  ''
            $'_SEGSIZE'                         =  ''
            $'_SEGMENT_DEVICE'                  =  ''
            $'_SELECT'                          =  ''
            $'_SEQUENCE'                        =  ''
            $'_SET'                             =  ''
            $'_SETS'                            =  ''
            $'_SMALLINT'                        =  ''
            $'_SNAPSHOT'                        =  ''
            $'_SNAPSHOT_LOG'                    =  ''
            $'_SQL_SERVER'                      =  ''
            $'_SQLID'                           =  ''
            $'_SSID'                            =  ''
            $'_STOGROUP'                        =  ''
            $'_SUBPAGES'                        =  ''
            $'_SUBPARTITION'                    =  ''
            $'_SUMMARY_TABLE'                   =  ''
            $'_SYBASE'                          =  ''
            $'_SYNONYM'                         =  ''
            $'_SYSTEM'                          =  ''
            $'_TABLE'                           =  ''
            $'_TABLESPACE'                      =  ''
            $'_TABLE_COLUMN'                    =  ''
            $'_TABLE_CLUSTER_KEY'               =  ''
            $'_TIME'                            =  ''
            $'_TIMESTAMP'                       =  ''
            $'_TO'                              =  ''
            $'_TRIGGER'                         =  ''
            $'_TRUNCATE'                        =  ''
            $'_TYPE'                            =  ''
            $'_UNIQUE'                          =  ''
            $'_UNIQUE_KEY'                      =  ''
            $'_USER'                            =  ''
            $'_USERMESSAGE'                     =  ''
            $'_VALIDPROC'                       =  ''
            $'_VALUES'                          =  ''
            $'_VARCHAR'                         =  ''
            $'_VARGRAPHIC'                      =  ''
            $'_VCAT'                            =  ''
            $'_VCATPASS'                        =  ''
            $'_VIEW'                            =  ''
            $'_VOLUMES'                         =  ''
            $'_WITH'                            =  ''
            $'_WHERE'                           =  ''
            $'_X'                               =  ''
            $'_YES'                             =  ''
            $'__BEGINBLOCK'                     =  ''
            $'__CDL'                            =  ''
            $'__DBMS'                           =  ''
            $'__DEST'                           =  ''
            $'__ENDBLOCK'                       =  ''
            $'__END_OCDL'                       =  ''
            $'__END_CDL'                        =  ''
            $'__GLID'                           =  ''
            $'__OCDL'                           =  ''
            $'__ORGN'                           =  ''
            $'__TIME'                           =  ''
            $'__TARGET'                         =  ''
            $'__TRUERELEASE'                    =  ''
            condition                           =  *$'_CONDITION_'
            query                               =  *$'_QUERY_BODY_'
                                                =  *REPOSTUFF | *repos_statements
            repos_statements                    =  *true_release_statement *target_statement
+                                               |  *target_statement *true_release_statement
            target_statement                    =  *$'__TARGET' *id $'.' *id $'.' *id
            true_release_statement              =  *$'__TRUERELEASE' *BLOCK_TEXT
            CDL                                 =  *ORA_preamble
+                                               |  *SQS_preamble
+                                               |  *SYB_preamble
+                                               |  *INF_preamble
+                                               |  *DB2_preamble
+                                               |  *ORA_preamble *ORA_statementList
+                                               |  *SQS_preamble *SYB_statementList
+                                               |  *SYB_preamble *SYB_statementList
+                                               |  *INF_preamble *INF_statementList
+                                               |  *DB2_preamble *DB2_statementList
+                                               |  *MVS_preamble
+                                               |  *MVS_preamble *MVS_statementList
                                                =  *ORA_preamble
            ORA_preamble                        =  *$'__DBMS' *$'_ORACLE'
            num                                 =  *NUMBER
+                                               |  *NEGNUMBER
+                                               |  *POSNUMBER
+                                               |  *DECIMAL
+                                               |  *POSDECIMAL
+                                               |  *NEGDECIMAL
+                                               |  *ENUMBER
            MVS_STR                             =  *id
+                                               |  $'*'
            MVS_preamble1                       =  *$'__TIME' *stmt_no *$'_sq_string_'
            MVS_preamble2                       =  *$'__ORGN'
+                                                  *stmt_no
+                                                  *$'_SSID'
+                                                  *MVS_STR
+                                                  *$'_LOCATION'
+                                                  *MVS_STR
+                                                  *$'_RELEASE'
+                                                  *$'_sq_string_'
            MVS_preamble3                       =  *$'__DEST' *stmt_no *$'_SSID' *MVS_STR *$'_LOCATION' *MVS_STR
            MVS_preamble4                       =  *$'__GLID' *stmt_no *SYMBOL *$'_GLOBAL' *$'_SETS' *$'_AUTHID'
            MVS_preamble                        =  *MVS_preamble1 *MVS_preamble2 *MVS_preamble3
+                                               |  *MVS_preamble1 *MVS_preamble2 *MVS_preamble3 *MVS_preamble4
            MVS_statementList_1                 =  *MVS_statement
            MVS_statementList                   =  *MVS_statementList_1
+                                               |  *MVS_statementList *MVS_statementList_1
            MVS_statement                       =  *$'__CDL' *stmt_no *mvs_s *$'__END_CDL'
+                                               |  *$'__CDL' *stmt_no *error *$'__END_CDL'
            SQS_preamble                        =  *$'__DBMS' *$'_SQL_SERVER'
            SYB_preamble                        =  *$'__DBMS' *$'_SYBASE'
            DB2_preamble                        =  *$'__DBMS' *$'_DB2'
            INF_statement                       =  *$'__OCDL' *stmt_no *inf_s *$'__END_OCDL'
+                                               |  *$'__OCDL' *stmt_no *error *$'__END_OCDL'
            ORA_statement                       =  *$'__OCDL' *stmt_no *ora_s *$'__END_OCDL'
+                                               |  *$'__OCDL' *stmt_no *error *$'__END_OCDL'
            SYB_statement                       =  *$'__OCDL' *stmt_no *syb_s *$'__END_OCDL'
+                                               |  *$'__OCDL' *stmt_no *error *$'__END_OCDL'
            DB2_statement                       =  *$'__OCDL' *stmt_no *db2_s *$'__END_OCDL'
+                                               |  *$'__OCDL' *stmt_no *error *$'__END_OCDL'
            INF_statementList                   =  *INF_statement
+                                               |  *INF_statementList *INF_statement
            ORA_statementList                   =  *ORA_statement
+                                               |  *ORA_statementList *ORA_statement
            SYB_statementList                   =  *SYB_statement
+                                               |  *SYB_statementList *SYB_statement
            DB2_statementList                   =  *DB2_statement
                                                =  *stmt_no
            stmt_no                             =  *number
            block                               =  *$'__BEGINBLOCK' *block_text *$'__ENDBLOCK'
            block_text                          =  *BLOCK_TEXT
+                                               |  *block_text *BLOCK_TEXT
            change                              =  *id *$'_CHANGED' *$'_TO' *factor
+                                               |  *id *$'_CHANGED' *$'_FROM' *factor *$'_TO' *factor
            changes                             =  *change
+                                               |  *changes *change
            attr                                =  *id *factor
            attrs                               =  *attr
+                                               |  *attrs *attr
            attrs_list                          =  *attrs
                                                =  *simpl_attrs
            simpl_attrs                         =  *attrs
            cmplx_attrs                         =  *attrs
+                                               |  $'(' *attrs_list $')'
+                                               |  *attrs $'(' *attrs_list $')'
            deep_attrs                          =  *attrs
+                                               |  $'(' *deep_attrs_list $')'
+                                               |  *attrs $'(' *deep_attrs_list $')'
            deep_attrs_list                     =  *nested_attrs
+                                               |  *deep_attrs_list $',' *nested_attrs
            nested_attrs                        =  *attrs
+                                               |  $'(' *deep_attrs_list $')'
+                                               |  *attrs $'(' *deep_attrs_list $')'
            factor                              =  *block
+                                               |  *lstring
+                                               |  *$'_NULL'
+                                               |  *number
+                                               |  *string
+                                               |  *symbol
+                                               |  *$'_sq_string_'
+                                               |  $'<' *$'_DEFLT' $'>'
            mvs_string_list                     =  *mvs_strings
            mvs_string                          =  *MVS_STR
+                                               |  *num
+                                               |  *$'_sq_string_'
            mvs_strings                         =  *mvs_string
+                                               |  *mvs_strings $',' *mvs_string
+                                               |  *mvs_strings *mvs_string
            number                              =  *NUMBER
            string                              =  *STRING
            symbol                              =  *SYMBOL
            lstring                             =  *lstring_beg *lstring_mid *lstring_end
            lstring_beg                         =  *LONG_STRING_BEG
                                                =  *lstring_mid
            lstring_mid                         =  *lstring_mid *LONG_STRING_MID
            nm_1                                =  *id
            nm_2                                =  *id $'.' *id
            nm_3                                =  *id $'.' *id $'.' *id
            nm_4                                =  *id $'.' *id $'.' *id $'.' *id
            nm_5                                =  *id $'.' *id $'.' *id $'.' *id $'.' *id
            id_d_1                              =  *id_d_2
+                                               |  *id_d_2 $'@' *id
            id_d_2                              =  *id
+                                               |  *id_d_2 $'.' *id
            nm_d                                =  *id $'.' *id_d_1
            nm_n_1                              =  *number
            nm_n_2                              =  *number $'.' *number
            nm_n                                =  *id $'.' *number
+                                               |  *number
            nm_num                              =  *number $'.' *string
            nm_c                                =  *nm_5
+                                               |  *nm_5 $';' *number
            nm_g                                =  *nm_3
+                                               |  *nm_3 $';' *number
            $'_sq_string_'                      =  *$'_SQ_STRING_'
            $'_dq_string_'                      =  *STRING
            id                                  =  *STRING
+                                               |  *SYMBOL
+                                               |  *UND_SYMBOL
+                                               |  *$'_ACTION'
+                                               |  *$'_ADD'
+                                               |  *$'_AFTER'
+                                               |  *$'_ALIAS'
+                                               |  *$'_ALL'
+                                               |  *$'_ALTER'
+                                               |  *$'_ANY'
+                                               |  *$'_AS'
+                                               |  *$'_ASC'
+                                               |  *$'_ASCII'
+                                               |  *$'_AUDIT'
+                                               |  *$'_BEFORE'
+                                               |  *$'_BIT'
+                                               |  *$'_BLOBSPACE'
+                                               |  *$'_BUFFERPOOL'
+                                               |  *$'_BY'
+                                               |  *$'_CAPTURE'
+                                               |  *$'_CASCADE'
+                                               |  *$'_CCSID'
+                                               |  *$'_CHANGED'
+                                               |  *$'_CHANGES'
+                                               |  *$'_CHAR'
+                                               |  *$'_CHECK'
+                                               |  *$'_CHUNK'
+                                               |  *$'_CLOSE'
+                                               |  *$'_CLUSTER'
+                                               |  *$'_COLCOMMENT'
+                                               |  *$'_COLLABEL'
+                                               |  *$'_COLUMN'
+                                               |  *$'_COLUMNS'
+                                               |  *$'_COMMENT'
+                                               |  *$'_COMPRESS'
+                                               |  *$'_CONTAINER'
+                                               |  *$'_CREATE'
+                                               |  *$'_CURRENT'
+                                               |  *$'_DATA'
+                                               |  *$'_DATABASE'
+                                               |  *$'_DATE'
+                                               |  *$'_DB2'
+                                               |  *$'_DBSPACE'
+                                               |  *$'_DECIMAL'
+                                               |  *$'_DEFAULT'
+                                               |  *$'_DEFAULTVALUE'
+                                               |  *$'_DEFLT'
+                                               |  *$'_DELETE'
+                                               |  *$'_DESC'
+                                               |  *$'_DROP'
+                                               |  *$'_DROPRESTRICT'
+                                               |  *$'_DSETPASS'
+                                               |  *$'_EBCDIC'
+                                               |  *$'_EDITPROC'
+                                               |  *$'_ERASE'
+                                               |  *$'_EXTENT'
+                                               |  *$'_FIELDPROC'
+                                               |  *$'_FILE'
+                                               |  *$'_FILEGROUP'
+                                               |  *$'_FLOAT'
+                                               |  *$'_FOR'
+                                               |  *$'_FOREIGN'
+                                               |  *$'_FRAGMENT'
+                                               |  *$'_FREEPAGE'
+                                               |  *$'_FROM'
+                                               |  *$'_FUNCTION'
+                                               |  *$'_G'
+                                               |  *$'_GPCACHE'
+                                               |  *$'_GRAPHIC'
+                                               |  *$'_GROUP'
+                                               |  *$'_HAVING'
+                                               |  *$'_HTMLREPORT'
+                                               |  *$'_INDEX'
+                                               |  *$'_INFORMIX'
+                                               |  *$'_INTEGER'
+                                               |  *$'_K'
+                                               |  *$'_KEY'
+                                               |  *$'_KEYCOLUMNS'
+                                               |  *$'_LABEL'
+                                               |  *$'_LOCAL'
+                                               |  *$'_LOCATION'
+                                               |  *$'_LOCKMAX'
+                                               |  *$'_LOCKSIZE'
+                                               |  *$'_LOGIN'
+                                               |  *$'_LONG'
+                                               |  *$'_M'
+                                               |  *$'_MEMBER'
+                                               |  *$'_MIGRATE'
+                                               |  *$'_MIGRATEDEPSONLY'
+                                               |  *$'_MODIFY'
+                                               |  *$'_MOVE'
+                                               |  *$'_N'
+                                               |  *$'_NAME'
+                                               |  *$'_NO'
+                                               |  *$'_NOCOLCOMMENT'
+                                               |  *$'_NOCOLLABEL'
+                                               |  *$'_NOCOLUMNS'
+                                               |  *$'_NOCOMMENT'
+                                               |  *$'_NODE'
+                                               |  *$'_NODEGROUP'
+                                               |  *$'_NODSETPASS'
+                                               |  *$'_NOEDITPROC'
+                                               |  *$'_NOLABEL'
+                                               |  *$'_NONE'
+                                               |  *$'_NOPRIMARYKEY'
+                                               |  *$'_NOSETPASS'
+                                               |  *$'_NOT'
+                                               |  *$'_NOTNULL'
+                                               |  *$'_NOVALIDPROC'
+                                               |  *$'_NOVCATPASS'
+                                               |  *$'_NULL'
+                                               |  *$'_NUMPARTS'
+                                               |  *$'_OBID'
+                                               |  *$'_ON'
+                                               |  *$'_OPTION'
+                                               |  *$'_ORACLE'
+                                               |  *$'_OWNER'
+                                               |  *$'_PACKAGE'
+                                               |  *$'_PAGE'
+                                               |  *$'_PARAMETER'
+                                               |  *$'_PART'
+                                               |  *$'_PARTITION'
+                                               |  *$'_PARTS'
+                                               |  *$'_PCTFREE'
+                                               |  *$'_PIECESIZE'
+                                               |  *$'_POSITION'
+                                               |  *$'_PRIMARYKEY'
+                                               |  *$'_PRIQTY'
+                                               |  *$'_PROCEDURE'
+                                               |  *$'_PROFILE'
+                                               |  *$'_QUALIFIED'
+                                               |  *$'_QUALIFIER'
+                                               |  *$'_QUOTA'
+                                               |  *$'_READ'
+                                               |  *$'_REBUILD'
+                                               |  *$'_RECOMPILE'
+                                               |  *$'_REFCOLUMNS'
+                                               |  *$'_REFERENCETB'
+                                               |  *$'_RELEASE'
+                                               |  *$'_RESOURCE'
+                                               |  *$'_RESTRICT'
+                                               |  *$'_RETURN'
+                                               |  *$'_ROLE'
+                                               |  *$'_ROSHARE'
+                                               |  *$'_ROW'
+                                               |  *$'_RULE'
+                                               |  *$'_SBCS'
+                                               |  *$'_SCHEMA'
+                                               |  *$'_SECQTY'
+                                               |  *$'_SEGMENT'
+                                               |  *$'_SEGSIZE'
+                                               |  *$'_SELECT'
+                                               |  *$'_SEQUENCE'
+                                               |  *$'_SET'
+                                               |  *$'_SMALLINT'
+                                               |  *$'_SNAPSHOT'
+                                               |  *$'_SQLID'
+                                               |  *$'_SQL_SERVER'
+                                               |  *$'_SSID'
+                                               |  *$'_STOGROUP'
+                                               |  *$'_SUBPAGES'
+                                               |  *$'_SYBASE'
+                                               |  *$'_SYNONYM'
+                                               |  *$'_SYSTEM'
+                                               |  *$'_TABLE'
+                                               |  *$'_TABLESPACE'
+                                               |  *$'_TIME'
+                                               |  *$'_TIMESTAMP'
+                                               |  *$'_TO'
+                                               |  *$'_TRIGGER'
+                                               |  *$'_TRUNCATE'
+                                               |  *$'_TYPE'
+                                               |  *$'_UNIQUE'
+                                               |  *$'_USER'
+                                               |  *$'_USERMESSAGE'
+                                               |  *$'_VALIDPROC'
+                                               |  *$'_VALUES'
+                                               |  *$'_VARCHAR'
+                                               |  *$'_VARGRAPHIC'
+                                               |  *$'_VCAT'
+                                               |  *$'_VCATPASS'
+                                               |  *$'_VIEW'
+                                               |  *$'_VOLUMES'
+                                               |  *$'_WHERE'
+                                               |  *$'_WITH'
+                                               |  *$'_X'
+                                               |  *$'_YES'
            inf_simpl_changes                   =  *changes
            inf_cmplx_changes                   =  *changes
+                                               |  $'(' *inf_sub_changes $')'
+                                               |  *changes $'(' *inf_sub_changes $')'
            inf_sub_changes                     =  *inf_sub_change
+                                               |  *inf_sub_changes $',' *inf_sub_change
            ora_simpl_changes                   =  *changes
            ora_cmplx_changes                   =  *changes
+                                               |  $'(' *ora_sub_changes $')'
+                                               |  *changes $'(' *ora_sub_changes $')'
            ora_sub_alters                      =  *changes
+                                               |  $'(' *ora_sub_changes $')'
+                                               |  *changes $'(' *ora_sub_changes $')'
            ora_sub_changes                     =  *ora_sub_change
+                                               |  *ora_sub_changes $',' *ora_sub_change
            syb_simpl_changes                   =  *changes
            syb_cmplx_changes                   =  *changes
+                                               |  $'(' *syb_sub_changes $')'
+                                               |  *changes $'(' *syb_sub_changes $')'
            syb_sub_changes                     =  *syb_sub_change
+                                               |  *syb_sub_changes $',' *syb_sub_change
            db2_cmplx_changes                   =  *changes
+                                               |  $'(' *db2_sub_changes $')'
+                                               |  *changes $'(' *db2_sub_changes $')'
            db2_sub_changes                     =  *db2_sub_change
+                                               |  *db2_sub_changes $',' *db2_sub_change
            inf_sub_change                      =  *$'_CREATE' *$'_COLUMN' *attrs
+                                               |  *$'_DROP' *$'_COLUMN' *nm_1
+                                               |  *$'_CREATE' *$'_FRAGMENT' *attrs
+                                               |  *$'_DROP' *$'_FRAGMENT' *nm_1
+                                               |  *$'_CREATE' *$'_CHUNK' *attrs
+                                               |  *$'_DROP' *$'_CHUNK' *nm_num
+                                               |  *$'_MODIFY' *$'_COLUMN' *nm_1 *id *$'_CHANGED' *$'_TO' *factor
+                                               |  *$'_MODIFY'
+                                                  *$'_COLUMN'
+                                                  *nm_1
+                                                  *id
+                                                  *$'_CHANGED'
+                                                  *$'_FROM'
+                                                  *factor
+                                                  *$'_TO'
+                                                  *factor
+                                               |  *$'_MODIFY'
+                                                  *$'_COLUMN'
+                                                  *nm_1
+                                                  *$'_FROM'
+                                                  *$'_POSITION'
+                                                  *number
+                                                  *$'_TO'
+                                                  *$'_POSITION'
+                                                  *number
+                                               |  *$'_MODIFY' *$'_FRAGMENT' *nm_1 *id *$'_CHANGED' *$'_TO' *factor
+                                               |  *$'_MODIFY'
+                                                  *$'_FRAGMENT'
+                                                  *nm_1
+                                                  *id
+                                                  *$'_CHANGED'
+                                                  *$'_FROM'
+                                                  *factor
+                                                  *$'_TO'
+                                                  *factor
+                                               |  *$'_MODIFY'
+                                                  *$'_FRAGMENT'
+                                                  *nm_1
+                                                  *$'_FROM'
+                                                  *$'_POSITION'
+                                                  *number
+                                                  *$'_TO'
+                                                  *$'_POSITION'
+                                                  *number
+                                               |  *$'_MODIFY' *$'_CHUNK' *nm_num *id *$'_CHANGED' *$'_TO' *factor
+                                               |  *$'_MODIFY'
+                                                  *$'_CHUNK'
+                                                  *nm_num
+                                                  *id
+                                                  *$'_CHANGED'
+                                                  *$'_FROM'
+                                                  *factor
+                                                  *$'_TO'
+                                                  *factor
+                                               |  *$'_MODIFY'
+                                                  *$'_CHUNK'
+                                                  *nm_num
+                                                  *$'_FROM'
+                                                  *$'_POSITION'
+                                                  *number
+                                                  *$'_TO'
+                                                  *$'_POSITION'
+                                                  *number
            ora_sub_change                      =  *$'_CREATE' *$'_COLUMN' *attrs
+                                               |  *$'_CREATE' *$'_EXTENT' *attrs
+                                               |  *$'_CREATE' *$'_FILE' *attrs
+                                               |  *$'_CREATE' *$'_MEMBER' *attrs
+                                               |  *$'_CREATE' *$'_PARTITION' *attrs
+                                               |  *$'_CREATE' *$'_QUOTA' *attrs
+                                               |  *$'_DROP' *$'_COLUMN' *nm_1
+                                               |  *$'_DROP' *$'_MEMBER' *nm_2
+                                               |  *$'_DROP' *$'_QUOTA' *nm_1
+                                               |  *$'_DROP' *$'_EXTENT' *number
+                                               |  *$'_DROP' *$'_FILE' *string
+                                               |  *$'_DROP' *$'_PARTITION' *nm_1
+                                               |  *$'_DROP' *$'_SUBPARTITION' *nm_1
+                                               |  *$'_MODIFY' *$'_COLUMN' *nm_1 *id *$'_CHANGED' *$'_TO' *factor
+                                               |  *$'_MODIFY'
+                                                  *$'_COLUMN'
+                                                  *nm_1
+                                                  *id
+                                                  *$'_CHANGED'
+                                                  *$'_FROM'
+                                                  *factor
+                                                  *$'_TO'
+                                                  *factor
+                                               |  *$'_MODIFY'
+                                                  *$'_COLUMN'
+                                                  *nm_1
+                                                  *$'_FROM'
+                                                  *$'_POSITION'
+                                                  *number
+                                                  *$'_TO'
+                                                  *$'_POSITION'
+                                                  *number
+                                               |  *$'_MODIFY' *$'_EXTENT' *number *id *$'_CHANGED' *$'_TO' *factor
+                                               |  *$'_MODIFY'
+                                                  *$'_EXTENT'
+                                                  *number
+                                                  *id
+                                                  *$'_CHANGED'
+                                                  *$'_FROM'
+                                                  *factor
+                                                  *$'_TO'
+                                                  *factor
+                                               |  *$'_MODIFY' *$'_FILE' *string *id *$'_CHANGED' *$'_TO' *factor
+                                               |  *$'_MODIFY'
+                                                  *$'_FILE'
+                                                  *string
+                                                  *id
+                                                  *$'_CHANGED'
+                                                  *$'_FROM'
+                                                  *factor
+                                                  *$'_TO'
+                                                  *factor
+                                               |  *$'_MODIFY'
+                                                  *$'_FILE'
+                                                  *string
+                                                  *$'_FROM'
+                                                  *$'_POSITION'
+                                                  *number
+                                                  *$'_TO'
+                                                  *$'_POSITION'
+                                                  *number
+                                               |  *$'_MODIFY'
+                                                  *$'_MEMBER'
+                                                  *nm_2
+                                                  *$'_FROM'
+                                                  *$'_POSITION'
+                                                  *number
+                                                  *$'_TO'
+                                                  *$'_POSITION'
+                                                  *number
+                                               |  *$'_MODIFY'
+                                                  *$'_PARTITION'
+                                                  *nm_1
+                                                  *$'_FROM'
+                                                  *$'_POSITION'
+                                                  *number
+                                                  *$'_TO'
+                                                  *$'_POSITION'
+                                                  *number
+                                               |  *$'_MODIFY'
+                                                  *$'_PARTITION'
+                                                  *nm_1
+                                                  *id
+                                                  *$'_CHANGED'
+                                                  *$'_FROM'
+                                                  *factor
+                                                  *$'_TO'
+                                                  *factor
+                                               |  *$'_MODIFY' *$'_QUOTA' *nm_1 *id *$'_CHANGED' *$'_TO' *factor
+                                               |  *$'_MODIFY'
+                                                  *$'_QUOTA'
+                                                  *nm_1
+                                                  *id
+                                                  *$'_CHANGED'
+                                                  *$'_FROM'
+                                                  *factor
+                                                  *$'_TO'
+                                                  *factor
+                                               |  *$'_MODIFY'
+                                                  *$'_QUOTA'
+                                                  *nm_1
+                                                  *$'_FROM'
+                                                  *$'_POSITION'
+                                                  *number
+                                                  *$'_TO'
+                                                  *$'_POSITION'
+                                                  *number
+                                               |  *$'_MODIFY' *$'_RESOURCE' *nm_1 *id *$'_CHANGED' *$'_TO' *factor
+                                               |  *$'_MODIFY'
+                                                  *$'_RESOURCE'
+                                                  *nm_1
+                                                  *id
+                                                  *$'_CHANGED'
+                                                  *$'_FROM'
+                                                  *factor
+                                                  *$'_TO'
+                                                  *factor
+                                               |  *$'_MODIFY'
+                                                  *$'_LOB_PARTITION'
+                                                  *nm_1
+                                                  *id
+                                                  *$'_CHANGED'
+                                                  *$'_FROM'
+                                                  *factor
+                                                  *$'_TO'
+                                                  *factor
+                                               |  *$'_MODIFY'
+                                                  *$'_LOB_SUBPARTITION'
+                                                  *nm_1
+                                                  *id
+                                                  *$'_CHANGED'
+                                                  *$'_FROM'
+                                                  *factor
+                                                  *$'_TO'
+                                                  *factor
+                                               |  *$'_ALTER' *$'_PARTITION' *nm_1 *ora_sub_alters
+                                               |  *$'_ALTER' *$'_SUBPARTITION' *nm_1 *ora_sub_alters
            syb_sub_change                      =  *$'_CREATE' *$'_ALIAS' *attrs
+                                               |  *$'_CREATE' *$'_COLUMN' *attrs
+                                               |  *$'_CREATE' *$'_DATABASE_DEVICE' *attrs
+                                               |  *$'_CREATE' *$'_SEGMENT_DEVICE' *attrs
+                                               |  *$'_DROP' *$'_ALIAS' *nm_2
+                                               |  *$'_DROP' *$'_COLUMN' *nm_1
+                                               |  *$'_DROP' *$'_COLUMN' *nm_2
+                                               |  *$'_DROP' *$'_DATABASE_DEVICE' *nm_1
+                                               |  *$'_DROP' *$'_SEGMENT_DEVICE' *nm_1
+                                               |  *$'_MODIFY' *$'_COLUMN' *nm_1 *id *$'_CHANGED' *$'_TO' *factor
+                                               |  *$'_MODIFY' *$'_COLUMN' *nm_2 *id *$'_CHANGED' *$'_TO' *factor
+                                               |  *$'_MODIFY'
+                                                  *$'_DATABASE_DEVICE'
+                                                  *nm_1
+                                                  *id
+                                                  *$'_CHANGED'
+                                                  *$'_TO'
+                                                  *factor
+                                               |  *$'_MODIFY'
+                                                  *$'_COLUMN'
+                                                  *nm_1
+                                                  *id
+                                                  *$'_CHANGED'
+                                                  *$'_FROM'
+                                                  *factor
+                                                  *$'_TO'
+                                                  *factor
+                                               |  *$'_MODIFY'
+                                                  *$'_COLUMN'
+                                                  *nm_2
+                                                  *id
+                                                  *$'_CHANGED'
+                                                  *$'_FROM'
+                                                  *factor
+                                                  *$'_TO'
+                                                  *factor
+                                               |  *$'_MODIFY'
+                                                  *$'_DATABASE_DEVICE'
+                                                  *nm_1
+                                                  *id
+                                                  *$'_CHANGED'
+                                                  *$'_FROM'
+                                                  *factor
+                                                  *$'_TO'
+                                                  *factor
+                                               |  *$'_MODIFY'
+                                                  *$'_ALIAS'
+                                                  *nm_2
+                                                  *$'_FROM'
+                                                  *$'_POSITION'
+                                                  *number
+                                                  *$'_TO'
+                                                  *$'_POSITION'
+                                                  *number
+                                               |  *$'_MODIFY'
+                                                  *$'_COLUMN'
+                                                  *nm_1
+                                                  *$'_FROM'
+                                                  *$'_POSITION'
+                                                  *number
+                                                  *$'_TO'
+                                                  *$'_POSITION'
+                                                  *number
+                                               |  *$'_MODIFY'
+                                                  *$'_COLUMN'
+                                                  *nm_2
+                                                  *$'_FROM'
+                                                  *$'_POSITION'
+                                                  *number
+                                                  *$'_TO'
+                                                  *$'_POSITION'
+                                                  *number
+                                               |  *$'_MODIFY'
+                                                  *$'_SEGMENT_DEVICE'
+                                                  *nm_1
+                                                  *$'_FROM'
+                                                  *$'_POSITION'
+                                                  *number
+                                                  *$'_TO'
+                                                  *$'_POSITION'
+                                                  *number
            db2_sub_change                      =  *$'_CREATE' *$'_COLUMN' *attrs
+                                               |  *$'_CREATE' *$'_CONTAINER' *attrs
+                                               |  *$'_CREATE' *$'_PARAMETER' *attrs
+                                               |  *$'_CREATE' *$'_RETURN' *attrs
+                                               |  *$'_CREATE' *$'_TABLE_COLUMN' *attrs
+                                               |  *$'_CREATE' *$'_NODE' *attrs
+                                               |  *$'_CREATE' *$'_BNODEGROUP' *attrs
+                                               |  *$'_DROP' *$'_COLUMN' *nm_1
+                                               |  *$'_DROP' *$'_CONTAINER' *nm_n_1
+                                               |  *$'_DROP' *$'_CONTAINER' *nm_n_2
+                                               |  *$'_DROP' *$'_PARAMETER' *nm_n
+                                               |  *$'_DROP' *$'_RETURN' *nm_1
+                                               |  *$'_DROP' *$'_TABLE_COLUMN' *nm_1
+                                               |  *$'_DROP' *$'_NODE' *nm_n
+                                               |  *$'_DROP' *$'_BNODEGROUP' *nm_1
+                                               |  *$'_MODIFY' *$'_COLUMN' *nm_1 *id *$'_CHANGED' *$'_TO' *factor
+                                               |  *$'_MODIFY'
+                                                  *$'_COLUMN'
+                                                  *nm_1
+                                                  *id
+                                                  *$'_CHANGED'
+                                                  *$'_FROM'
+                                                  *factor
+                                                  *$'_TO'
+                                                  *factor
+                                               |  *$'_MODIFY'
+                                                  *$'_COLUMN'
+                                                  *nm_1
+                                                  *$'_FROM'
+                                                  *$'_POSITION'
+                                                  *number
+                                                  *$'_TO'
+                                                  *$'_POSITION'
+                                                  *number
+                                               |  *$'_MODIFY' *$'_CONTAINER' *nm_n_1 *id *$'_CHANGED' *$'_TO' *factor
+                                               |  *$'_MODIFY'
+                                                  *$'_CONTAINER'
+                                                  *nm_n_1
+                                                  *id
+                                                  *$'_CHANGED'
+                                                  *$'_FROM'
+                                                  *factor
+                                                  *$'_TO'
+                                                  *factor
+                                               |  *$'_MODIFY'
+                                                  *$'_CONTAINER'
+                                                  *nm_n_1
+                                                  *$'_FROM'
+                                                  *$'_POSITION'
+                                                  *number
+                                                  *$'_TO'
+                                                  *$'_POSITION'
+                                                  *number
+                                               |  *$'_MODIFY' *$'_CONTAINER' *nm_n_2 *id *$'_CHANGED' *$'_TO' *factor
+                                               |  *$'_MODIFY'
+                                                  *$'_CONTAINER'
+                                                  *nm_n_2
+                                                  *id
+                                                  *$'_CHANGED'
+                                                  *$'_FROM'
+                                                  *factor
+                                                  *$'_TO'
+                                                  *factor
+                                               |  *$'_MODIFY'
+                                                  *$'_CONTAINER'
+                                                  *nm_n_2
+                                                  *$'_FROM'
+                                                  *$'_POSITION'
+                                                  *number
+                                                  *$'_TO'
+                                                  *$'_POSITION'
+                                                  *number
+                                               |  *$'_MODIFY' *$'_PARAMETER' *nm_n *id *$'_CHANGED' *$'_TO' *factor
+                                               |  *$'_MODIFY'
+                                                  *$'_PARAMETER'
+                                                  *nm_n
+                                                  *id
+                                                  *$'_CHANGED'
+                                                  *$'_FROM'
+                                                  *factor
+                                                  *$'_TO'
+                                                  *factor
+                                               |  *$'_MODIFY'
+                                                  *$'_PARAMETER'
+                                                  *nm_n
+                                                  *$'_FROM'
+                                                  *$'_POSITION'
+                                                  *number
+                                                  *$'_TO'
+                                                  *$'_POSITION'
+                                                  *number
+                                               |  *$'_MODIFY' *$'_RETURN' *nm_1 *id *$'_CHANGED' *$'_TO' *factor
+                                               |  *$'_MODIFY'
+                                                  *$'_RETURN'
+                                                  *nm_1
+                                                  *id
+                                                  *$'_CHANGED'
+                                                  *$'_FROM'
+                                                  *factor
+                                                  *$'_TO'
+                                                  *factor
+                                               |  *$'_MODIFY'
+                                                  *$'_RETURN'
+                                                  *nm_1
+                                                  *$'_FROM'
+                                                  *$'_POSITION'
+                                                  *number
+                                                  *$'_TO'
+                                                  *$'_POSITION'
+                                                  *number
+                                               |  *$'_MODIFY' *$'_TABLE_COLUMN' *nm_1 *id *$'_CHANGED' *$'_TO' *factor
+                                               |  *$'_MODIFY'
+                                                  *$'_TABLE_COLUMN'
+                                                  *nm_1
+                                                  *id
+                                                  *$'_CHANGED'
+                                                  *$'_FROM'
+                                                  *factor
+                                                  *$'_TO'
+                                                  *factor
+                                               |  *$'_MODIFY'
+                                                  *$'_TABLE_COLUMN'
+                                                  *nm_1
+                                                  *$'_FROM'
+                                                  *$'_POSITION'
+                                                  *number
+                                                  *$'_TO'
+                                                  *$'_POSITION'
+                                                  *number
+                                               |  *$'_MODIFY' *$'_NODE' *nm_n *id *$'_CHANGED' *$'_TO' *factor
+                                               |  *$'_MODIFY'
+                                                  *$'_NODE'
+                                                  *nm_n
+                                                  *id
+                                                  *$'_CHANGED'
+                                                  *$'_FROM'
+                                                  *factor
+                                                  *$'_TO'
+                                                  *factor
+                                               |  *$'_MODIFY'
+                                                  *$'_NODE'
+                                                  *nm_n
+                                                  *$'_FROM'
+                                                  *$'_POSITION'
+                                                  *number
+                                                  *$'_TO'
+                                                  *$'_POSITION'
+                                                  *number
+                                               |  *$'_MODIFY' *$'_BNODEGROUP' *nm_1 *id *$'_CHANGED' *$'_TO' *factor
+                                               |  *$'_MODIFY'
+                                                  *$'_BNODEGROUP'
+                                                  *nm_1
+                                                  *id
+                                                  *$'_CHANGED'
+                                                  *$'_FROM'
+                                                  *factor
+                                                  *$'_TO'
+                                                  *factor
+                                               |  *$'_MODIFY'
+                                                  *$'_BNODEGROUP'
+                                                  *nm_1
+                                                  *$'_FROM'
+                                                  *$'_POSITION'
+                                                  *number
+                                                  *$'_TO'
+                                                  *$'_POSITION'
+                                                  *number
            inf_s                               =  *$'_ALTER' *$'_BLOBSPACE' *nm_2 *inf_cmplx_changes
+                                               |  *$'_ALTER' *$'_CHECK' *nm_3 *inf_simpl_changes
+                                               |  *$'_ALTER' *$'_DBSPACE' *nm_2 *inf_cmplx_changes
+                                               |  *$'_ALTER' *$'_DATABASE' *nm_1 *inf_simpl_changes
+                                               |  *$'_ALTER' *$'_FOREIGN_KEY' *nm_3 *inf_cmplx_changes
+                                               |  *$'_ALTER' *$'_INDEX' *nm_3 *inf_cmplx_changes
+                                               |  *$'_ALTER' *$'_PRIMARY_KEY' *nm_3 *inf_cmplx_changes
+                                               |  *$'_ALTER' *$'_PROCEDURE' *nm_3 *inf_simpl_changes
+                                               |  *$'_ALTER' *$'_ROLE' *nm_2 *inf_simpl_changes
+                                               |  *$'_ALTER' *$'_SYNONYM' *nm_3 *inf_simpl_changes
+                                               |  *$'_ALTER' *$'_TABLE' *nm_3 *inf_cmplx_changes
+                                               |  *$'_ALTER' *$'_TRIGGER' *nm_3 *inf_simpl_changes
+                                               |  *$'_ALTER' *$'_UNIQUE_KEY' *nm_3 *inf_cmplx_changes
+                                               |  *$'_ALTER' *$'_USER' *nm_2 *inf_simpl_changes
+                                               |  *$'_ALTER' *$'_VIEW' *nm_3 *inf_cmplx_changes
+                                               |  *$'_CREATE' *$'_BLOBSPACE' *nm_2 *cmplx_attrs
+                                               |  *$'_CREATE' *$'_CHECK' *nm_3 *simpl_attrs
+                                               |  *$'_CREATE' *$'_DBSPACE' *nm_2 *cmplx_attrs
+                                               |  *$'_CREATE' *$'_DATABASE' *nm_1 *simpl_attrs
+                                               |  *$'_CREATE' *$'_FOREIGN_KEY' *nm_3 *cmplx_attrs
+                                               |  *$'_CREATE' *$'_INDEX' *nm_3 *cmplx_attrs
+                                               |  *$'_CREATE' *$'_PRIMARY_KEY' *nm_3 *cmplx_attrs
+                                               |  *$'_CREATE' *$'_PROCEDURE' *nm_3 *simpl_attrs
+                                               |  *$'_CREATE' *$'_ROLE' *nm_2 *simpl_attrs
+                                               |  *$'_CREATE' *$'_SYNONYM' *nm_3 *simpl_attrs
+                                               |  *$'_CREATE' *$'_TABLE' *nm_3 *cmplx_attrs
+                                               |  *$'_CREATE' *$'_TRIGGER' *nm_3 *simpl_attrs
+                                               |  *$'_CREATE' *$'_UNIQUE_KEY' *nm_3 *cmplx_attrs
+                                               |  *$'_CREATE' *$'_USER' *nm_2 *simpl_attrs
+                                               |  *$'_CREATE' *$'_VIEW' *nm_3 *cmplx_attrs
+                                               |  *$'_DROP' *$'_BLOBSPACE' *nm_2
+                                               |  *$'_DROP' *$'_CHECK' *nm_3
+                                               |  *$'_DROP' *$'_DBSPACE' *nm_2
+                                               |  *$'_DROP' *$'_DATABASE' *nm_1
+                                               |  *$'_DROP' *$'_FOREIGN_KEY' *nm_3
+                                               |  *$'_DROP' *$'_INDEX' *nm_3
+                                               |  *$'_DROP' *$'_PRIMARY_KEY' *nm_3
+                                               |  *$'_DROP' *$'_PROCEDURE' *nm_3
+                                               |  *$'_DROP' *$'_ROLE' *nm_2
+                                               |  *$'_DROP' *$'_SYNONYM' *nm_3
+                                               |  *$'_DROP' *$'_TABLE' *nm_3
+                                               |  *$'_DROP' *$'_TRIGGER' *nm_3
+                                               |  *$'_DROP' *$'_UNIQUE_KEY' *nm_3
+                                               |  *$'_DROP' *$'_USER' *nm_2
+                                               |  *$'_DROP' *$'_VIEW' *nm_3
+                                               |  *$'_MIGRATE' *$'_BLOBSPACE' *nm_2
+                                               |  *$'_MIGRATE' *$'_CHECK' *nm_3
+                                               |  *$'_MIGRATE' *$'_DBSPACE' *nm_2
+                                               |  *$'_MIGRATE' *$'_DATABASE' *nm_1
+                                               |  *$'_MIGRATE' *$'_FOREIGN_KEY' *nm_3
+                                               |  *$'_MIGRATE' *$'_INDEX' *nm_3
+                                               |  *$'_MIGRATE' *$'_PRIMARY_KEY' *nm_3
+                                               |  *$'_MIGRATE' *$'_PROCEDURE' *nm_3
+                                               |  *$'_MIGRATE' *$'_ROLE' *nm_2
+                                               |  *$'_MIGRATE' *$'_SYNONYM' *nm_3
+                                               |  *$'_MIGRATE' *$'_TABLE' *nm_3
+                                               |  *$'_MIGRATE' *$'_TRIGGER' *nm_3
+                                               |  *$'_MIGRATE' *$'_UNIQUE_KEY' *nm_3
+                                               |  *$'_MIGRATE' *$'_USER' *nm_2
+                                               |  *$'_MIGRATE' *$'_VIEW' *nm_3
+                                               |  *$'_REBUILD' *$'_BLOBSPACE' *nm_2
+                                               |  *$'_REBUILD' *$'_DBSPACE' *nm_2
+                                               |  *$'_REBUILD' *$'_DATABASE' *nm_1
+                                               |  *$'_REBUILD' *$'_FOREIGN_KEY' *nm_3
+                                               |  *$'_REBUILD' *$'_INDEX' *nm_3
+                                               |  *$'_REBUILD' *$'_PRIMARY_KEY' *nm_3
+                                               |  *$'_REBUILD' *$'_TABLE' *nm_3
+                                               |  *$'_REBUILD' *$'_UNIQUE_KEY' *nm_3
+                                               |  *$'_TRUNCATE' *$'_TABLE' *nm_3
            ora_s                               =  *$'_ALTER' *$'_CHECK' *nm_2 *ora_simpl_changes
+                                               |  *$'_ALTER' *$'_CLUSTER' *nm_2 *ora_cmplx_changes
+                                               |  *$'_ALTER' *$'_DATABASE_LINK' *nm_d *ora_simpl_changes
+                                               |  *$'_ALTER' *$'_FOREIGN_KEY' *nm_2 *ora_cmplx_changes
+                                               |  *$'_ALTER' *$'_FUNCTION' *nm_2 *ora_cmplx_changes
+                                               |  *$'_ALTER' *$'_INDEX' *nm_2 *ora_cmplx_changes
+                                               |  *$'_ALTER' *$'_PACKAGE' *nm_2 *ora_cmplx_changes
+                                               |  *$'_ALTER' *$'_PACKAGE_BODY' *nm_2 *ora_cmplx_changes
+                                               |  *$'_ALTER' *$'_PRIMARY_KEY' *nm_2 *ora_cmplx_changes
+                                               |  *$'_ALTER' *$'_PROCEDURE' *nm_2 *ora_cmplx_changes
+                                               |  *$'_ALTER' *$'_PROFILE' *nm_1 *ora_cmplx_changes
+                                               |  *$'_ALTER' *$'_REFRESH_GROUP' *nm_2 *ora_cmplx_changes
+                                               |  *$'_ALTER' *$'_ROLE' *nm_1 *ora_simpl_changes
+                                               |  *$'_ALTER' *$'_ROLLBACK_SEGMENT' *nm_1 *ora_simpl_changes
+                                               |  *$'_ALTER' *$'_SEQUENCE' *nm_2 *ora_simpl_changes
+                                               |  *$'_ALTER' *$'_SNAPSHOT' *nm_2 *ora_cmplx_changes
+                                               |  *$'_ALTER' *$'_SNAPSHOT_LOG' *nm_2 *ora_simpl_changes
+                                               |  *$'_ALTER' *$'_SYNONYM' *nm_2 *ora_simpl_changes
+                                               |  *$'_ALTER' *$'_TABLE' *nm_2 *ora_cmplx_changes
+                                               |  *$'_ALTER' *$'_TABLE_CLUSTER_KEY' *nm_2 *ora_cmplx_changes
+                                               |  *$'_ALTER' *$'_TABLESPACE' *nm_1 *ora_cmplx_changes
+                                               |  *$'_ALTER' *$'_TRIGGER' *nm_2 *ora_cmplx_changes
+                                               |  *$'_ALTER' *$'_UNIQUE_KEY' *nm_2 *ora_cmplx_changes
+                                               |  *$'_ALTER' *$'_USER' *nm_1 *ora_cmplx_changes
+                                               |  *$'_ALTER' *$'_VIEW' *nm_2 *ora_cmplx_changes
+                                               |  *$'_CREATE' *$'_CHECK' *nm_2 *simpl_attrs
+                                               |  *$'_CREATE' *$'_CLUSTER' *nm_2 *cmplx_attrs
+                                               |  *$'_CREATE' *$'_DATABASE_LINK' *nm_d *simpl_attrs
+                                               |  *$'_CREATE' *$'_DIRECTORY' *nm_1 *simpl_attrs
+                                               |  *$'_CREATE' *$'_FOREIGN_KEY' *nm_2 *cmplx_attrs
+                                               |  *$'_CREATE' *$'_FUNCTION' *nm_2 *cmplx_attrs
+                                               |  *$'_CREATE' *$'_INDEX' *nm_2 *deep_attrs
+                                               |  *$'_CREATE' *$'_LOB_OBJECT' *nm_3 *simpl_attrs
+                                               |  *$'_CREATE' *$'_PACKAGE' *nm_2 *cmplx_attrs
+                                               |  *$'_CREATE' *$'_PACKAGE_BODY' *nm_2 *cmplx_attrs
+                                               |  *$'_CREATE' *$'_PRIMARY_KEY' *nm_2 *cmplx_attrs
+                                               |  *$'_CREATE' *$'_PROCEDURE' *nm_2 *cmplx_attrs
+                                               |  *$'_CREATE' *$'_PROFILE' *nm_1 *cmplx_attrs
+                                               |  *$'_CREATE' *$'_REFRESH_GROUP' *nm_2 *cmplx_attrs
+                                               |  *$'_CREATE' *$'_ROLE' *nm_1 *simpl_attrs
+                                               |  *$'_CREATE' *$'_ROLLBACK_SEGMENT' *nm_1 *simpl_attrs
+                                               |  *$'_CREATE' *$'_SEQUENCE' *nm_2 *simpl_attrs
+                                               |  *$'_CREATE' *$'_SNAPSHOT' *nm_2 *cmplx_attrs
+                                               |  *$'_CREATE' *$'_SNAPSHOT_LOG' *nm_2 *simpl_attrs
+                                               |  *$'_CREATE' *$'_SYNONYM' *nm_2 *simpl_attrs
+                                               |  *$'_CREATE' *$'_TABLE' *nm_2 *deep_attrs
+                                               |  *$'_CREATE' *$'_TABLE_CLUSTER_KEY' *nm_2 *cmplx_attrs
+                                               |  *$'_CREATE' *$'_TABLESPACE' *nm_1 *cmplx_attrs
+                                               |  *$'_CREATE' *$'_TRIGGER' *nm_2 *cmplx_attrs
+                                               |  *$'_CREATE' *$'_UNIQUE_KEY' *nm_2 *cmplx_attrs
+                                               |  *$'_CREATE' *$'_USER' *nm_1 *cmplx_attrs
+                                               |  *$'_CREATE' *$'_VIEW' *nm_2 *cmplx_attrs
+                                               |  *$'_DROP' *$'_CHECK' *nm_2
+                                               |  *$'_DROP' *$'_CLUSTER' *nm_2
+                                               |  *$'_DROP' *$'_DATABASE_LINK' *nm_d
+                                               |  *$'_DROP' *$'_DIRECTORY' *nm_1
+                                               |  *$'_DROP' *$'_FOREIGN_KEY' *nm_2
+                                               |  *$'_DROP' *$'_FUNCTION' *nm_2
+                                               |  *$'_DROP' *$'_INDEX' *nm_2
+                                               |  *$'_DROP' *$'_PACKAGE' *nm_2
+                                               |  *$'_DROP' *$'_PACKAGE_BODY' *nm_2
+                                               |  *$'_DROP' *$'_PRIMARY_KEY' *nm_2
+                                               |  *$'_DROP' *$'_PROCEDURE' *nm_2
+                                               |  *$'_DROP' *$'_PROFILE' *nm_1
+                                               |  *$'_DROP' *$'_REFRESH_GROUP' *nm_2
+                                               |  *$'_DROP' *$'_ROLE' *nm_1
+                                               |  *$'_DROP' *$'_ROLLBACK_SEGMENT' *nm_1
+                                               |  *$'_DROP' *$'_SEQUENCE' *nm_2
+                                               |  *$'_DROP' *$'_SNAPSHOT' *nm_2
+                                               |  *$'_DROP' *$'_SNAPSHOT_LOG' *nm_2
+                                               |  *$'_DROP' *$'_SYNONYM' *nm_2
+                                               |  *$'_DROP' *$'_TABLE' *nm_2
+                                               |  *$'_DROP' *$'_TABLE_CLUSTER_KEY' *nm_2
+                                               |  *$'_DROP' *$'_TABLESPACE' *nm_1
+                                               |  *$'_DROP' *$'_TRIGGER' *nm_2
+                                               |  *$'_DROP' *$'_UNIQUE_KEY' *nm_2
+                                               |  *$'_DROP' *$'_USER' *nm_1
+                                               |  *$'_DROP' *$'_VIEW' *nm_2
+                                               |  *$'_MIGRATE' *$'_CHECK' *nm_2
+                                               |  *$'_MIGRATE' *$'_CLUSTER' *nm_2
+                                               |  *$'_MIGRATE' *$'_DATABASE_LINK' *nm_d
+                                               |  *$'_MIGRATE' *$'_FOREIGN_KEY' *nm_2
+                                               |  *$'_MIGRATE' *$'_FUNCTION' *nm_2
+                                               |  *$'_MIGRATE' *$'_INDEX' *nm_2
+                                               |  *$'_MIGRATE' *$'_PACKAGE' *nm_2
+                                               |  *$'_MIGRATE' *$'_PACKAGE_BODY' *nm_2
+                                               |  *$'_MIGRATE' *$'_PRIMARY_KEY' *nm_2
+                                               |  *$'_MIGRATE' *$'_PROCEDURE' *nm_2
+                                               |  *$'_MIGRATE' *$'_PROFILE' *nm_1
+                                               |  *$'_MIGRATE' *$'_REFRESH_GROUP' *nm_2
+                                               |  *$'_MIGRATE' *$'_ROLE' *nm_1
+                                               |  *$'_MIGRATE' *$'_ROLLBACK_SEGMENT' *nm_1
+                                               |  *$'_MIGRATE' *$'_SEQUENCE' *nm_2
+                                               |  *$'_MIGRATE' *$'_SNAPSHOT' *nm_2
+                                               |  *$'_MIGRATE' *$'_SNAPSHOT_LOG' *nm_2
+                                               |  *$'_MIGRATE' *$'_SYNONYM' *nm_2
+                                               |  *$'_MIGRATE' *$'_TABLE' *nm_2
+                                               |  *$'_MIGRATE' *$'_TABLESPACE' *nm_1
+                                               |  *$'_MIGRATE' *$'_TRIGGER' *nm_2
+                                               |  *$'_MIGRATE' *$'_UNIQUE_KEY' *nm_2
+                                               |  *$'_MIGRATE' *$'_USER' *nm_1
+                                               |  *$'_MIGRATE' *$'_VIEW' *nm_2
+                                               |  *$'_HTMLREPORT' *$'_CHECK' *nm_2
+                                               |  *$'_HTMLREPORT' *$'_CLUSTER' *nm_2
+                                               |  *$'_HTMLREPORT' *$'_DATABASE_LINK' *nm_d
+                                               |  *$'_HTMLREPORT' *$'_FOREIGN_KEY' *nm_2
+                                               |  *$'_HTMLREPORT' *$'_FUNCTION' *nm_2
+                                               |  *$'_HTMLREPORT' *$'_INDEX' *nm_2
+                                               |  *$'_HTMLREPORT' *$'_PACKAGE' *nm_2
+                                               |  *$'_HTMLREPORT' *$'_PACKAGE_BODY' *nm_2
+                                               |  *$'_HTMLREPORT' *$'_PRIMARY_KEY' *nm_2
+                                               |  *$'_HTMLREPORT' *$'_PROCEDURE' *nm_2
+                                               |  *$'_HTMLREPORT' *$'_PROFILE' *nm_1
+                                               |  *$'_HTMLREPORT' *$'_REFRESH_GROUP' *nm_2
+                                               |  *$'_HTMLREPORT' *$'_ROLE' *nm_1
+                                               |  *$'_HTMLREPORT' *$'_ROLLBACK_SEGMENT' *nm_1
+                                               |  *$'_HTMLREPORT' *$'_SEQUENCE' *nm_2
+                                               |  *$'_HTMLREPORT' *$'_SNAPSHOT' *nm_2
+                                               |  *$'_HTMLREPORT' *$'_SNAPSHOT_LOG' *nm_2
+                                               |  *$'_HTMLREPORT' *$'_SYNONYM' *nm_2
+                                               |  *$'_HTMLREPORT' *$'_TABLE' *nm_2
+                                               |  *$'_HTMLREPORT' *$'_TABLESPACE' *nm_1
+                                               |  *$'_HTMLREPORT' *$'_TRIGGER' *nm_2
+                                               |  *$'_HTMLREPORT' *$'_UNIQUE_KEY' *nm_2
+                                               |  *$'_HTMLREPORT' *$'_USER' *nm_1
+                                               |  *$'_HTMLREPORT' *$'_VIEW' *nm_2
+                                               |  *$'_REBUILD' *$'_CLUSTER' *nm_2
+                                               |  *$'_REBUILD' *$'_INDEX' *nm_2
+                                               |  *$'_REBUILD' *$'_PRIMARY_KEY' *nm_2
+                                               |  *$'_REBUILD' *$'_ROLLBACK_SEGMENT' *nm_1
+                                               |  *$'_REBUILD' *$'_SNAPSHOT' *nm_2
+                                               |  *$'_REBUILD' *$'_SNAPSHOT_LOG' *nm_2
+                                               |  *$'_REBUILD' *$'_TABLE' *nm_2
+                                               |  *$'_REBUILD' *$'_TABLESPACE' *nm_1
+                                               |  *$'_REBUILD' *$'_UNIQUE_KEY' *nm_2
+                                               |  *$'_RECOMPILE' *$'_FUNCTION' *nm_2
+                                               |  *$'_RECOMPILE' *$'_PACKAGE' *nm_2
+                                               |  *$'_RECOMPILE' *$'_PACKAGE_BODY' *nm_2
+                                               |  *$'_RECOMPILE' *$'_PROCEDURE' *nm_2
+                                               |  *$'_RECOMPILE' *$'_SNAPSHOT' *nm_2
+                                               |  *$'_RECOMPILE' *$'_TRIGGER' *nm_2
+                                               |  *$'_RECOMPILE' *$'_VIEW' *nm_2
            syb_s                               =  *$'_ALTER' *$'_CHECK' *nm_3 *syb_simpl_changes
+                                               |  *$'_ALTER' *$'_DATABASE' *nm_1 *syb_cmplx_changes
+                                               |  *$'_ALTER' *$'_DEFAULT' *nm_3 *syb_simpl_changes
+                                               |  *$'_ALTER' *$'_FOREIGN_KEY' *nm_4 *syb_cmplx_changes
+                                               |  *$'_ALTER' *$'_GROUP' *nm_2 *syb_simpl_changes
+                                               |  *$'_ALTER' *$'_INDEX' *nm_4 *syb_cmplx_changes
+                                               |  *$'_ALTER' *$'_LOGICAL_COMMONKEY' *nm_c *syb_cmplx_changes
+                                               |  *$'_ALTER' *$'_LOGICAL_FOREIGNKEY' *nm_5 *syb_cmplx_changes
+                                               |  *$'_ALTER' *$'_LOGICAL_PRIMARYKEY' *nm_3 *syb_cmplx_changes
+                                               |  *$'_ALTER' *$'_LOGIN' *nm_2 *syb_simpl_changes
+                                               |  *$'_ALTER' *$'_PRIMARY_KEY' *nm_4 *syb_cmplx_changes
+                                               |  *$'_ALTER' *$'_PROCEDURE' *nm_g *syb_simpl_changes
+                                               |  *$'_ALTER' *$'_RULE' *nm_3 *syb_simpl_changes
+                                               |  *$'_ALTER' *$'_SEGMENT' *nm_2 *syb_cmplx_changes
+                                               |  *$'_ALTER' *$'_TABLE' *nm_3 *syb_cmplx_changes
+                                               |  *$'_ALTER' *$'_TRIGGER' *nm_3 *syb_simpl_changes
+                                               |  *$'_ALTER' *$'_UNIQUE_KEY' *nm_4 *syb_cmplx_changes
+                                               |  *$'_ALTER' *$'_USER' *nm_2 *syb_cmplx_changes
+                                               |  *$'_ALTER' *$'_USERMESSAGE' *nm_n *syb_simpl_changes
+                                               |  *$'_ALTER' *$'_VIEW' *nm_3 *syb_cmplx_changes
+                                               |  *$'_CREATE' *$'_CHECK' *nm_3 *simpl_attrs
+                                               |  *$'_CREATE' *$'_DATABASE' *nm_1 *cmplx_attrs
+                                               |  *$'_CREATE' *$'_DEFAULT' *nm_3 *simpl_attrs
+                                               |  *$'_CREATE' *$'_FOREIGN_KEY' *nm_4 *cmplx_attrs
+                                               |  *$'_CREATE' *$'_GROUP' *nm_2 *simpl_attrs
+                                               |  *$'_CREATE' *$'_INDEX' *nm_4 *cmplx_attrs
+                                               |  *$'_CREATE' *$'_LOGICAL_COMMONKEY' *nm_c *cmplx_attrs
+                                               |  *$'_CREATE' *$'_LOGICAL_FOREIGNKEY' *nm_5 *cmplx_attrs
+                                               |  *$'_CREATE' *$'_LOGICAL_PRIMARYKEY' *nm_3 *cmplx_attrs
+                                               |  *$'_CREATE' *$'_LOGIN' *nm_2 *simpl_attrs
+                                               |  *$'_CREATE' *$'_PRIMARY_KEY' *nm_4 *cmplx_attrs
+                                               |  *$'_CREATE' *$'_PROCEDURE' *nm_g *simpl_attrs
+                                               |  *$'_CREATE' *$'_RULE' *nm_3 *simpl_attrs
+                                               |  *$'_CREATE' *$'_SEGMENT' *nm_2 *cmplx_attrs
+                                               |  *$'_CREATE' *$'_TABLE' *nm_3 *cmplx_attrs
+                                               |  *$'_CREATE' *$'_TRIGGER' *nm_3 *simpl_attrs
+                                               |  *$'_CREATE' *$'_UNIQUE_KEY' *nm_4 *cmplx_attrs
+                                               |  *$'_CREATE' *$'_USER' *nm_2 *cmplx_attrs
+                                               |  *$'_CREATE' *$'_USERMESSAGE' *nm_n *simpl_attrs
+                                               |  *$'_CREATE' *$'_VIEW' *nm_3 *cmplx_attrs
+                                               |  *$'_DROP' *$'_CHECK' *nm_3
+                                               |  *$'_DROP' *$'_DATABASE' *nm_1
+                                               |  *$'_DROP' *$'_DEFAULT' *nm_3
+                                               |  *$'_DROP' *$'_FOREIGN_KEY' *nm_4
+                                               |  *$'_DROP' *$'_GROUP' *nm_2
+                                               |  *$'_DROP' *$'_INDEX' *nm_4
+                                               |  *$'_DROP' *$'_LOGICAL_COMMONKEY' *nm_c
+                                               |  *$'_DROP' *$'_LOGICAL_FOREIGNKEY' *nm_5
+                                               |  *$'_DROP' *$'_LOGICAL_PRIMARYKEY' *nm_3
+                                               |  *$'_DROP' *$'_LOGIN' *nm_2
+                                               |  *$'_DROP' *$'_PRIMARY_KEY' *nm_4
+                                               |  *$'_DROP' *$'_PROCEDURE' *nm_g
+                                               |  *$'_DROP' *$'_RULE' *nm_3
+                                               |  *$'_DROP' *$'_SEGMENT' *nm_2
+                                               |  *$'_DROP' *$'_TABLE' *nm_3
+                                               |  *$'_DROP' *$'_TRIGGER' *nm_3
+                                               |  *$'_DROP' *$'_UNIQUE_KEY' *nm_4
+                                               |  *$'_DROP' *$'_USER' *nm_2
+                                               |  *$'_DROP' *$'_USERMESSAGE' *nm_n
+                                               |  *$'_DROP' *$'_VIEW' *nm_3
+                                               |  *$'_MIGRATE' *$'_CHECK' *nm_3
+                                               |  *$'_MIGRATE' *$'_DATABASE' *nm_1
+                                               |  *$'_MIGRATE' *$'_DEFAULT' *nm_3
+                                               |  *$'_MIGRATE' *$'_FOREIGN_KEY' *nm_4
+                                               |  *$'_MIGRATE' *$'_GROUP' *nm_2
+                                               |  *$'_MIGRATE' *$'_INDEX' *nm_4
+                                               |  *$'_MIGRATE' *$'_LOGICAL_COMMONKEY' *nm_c
+                                               |  *$'_MIGRATE' *$'_LOGICAL_FOREIGNKEY' *nm_5
+                                               |  *$'_MIGRATE' *$'_LOGICAL_PRIMARYKEY' *nm_3
+                                               |  *$'_MIGRATE' *$'_LOGIN' *nm_2
+                                               |  *$'_MIGRATE' *$'_PRIMARY_KEY' *nm_4
+                                               |  *$'_MIGRATE' *$'_PROCEDURE' *nm_g
+                                               |  *$'_MIGRATE' *$'_RULE' *nm_3
+                                               |  *$'_MIGRATE' *$'_SEGMENT' *nm_2
+                                               |  *$'_MIGRATE' *$'_TABLE' *nm_3
+                                               |  *$'_MIGRATE' *$'_TRIGGER' *nm_3
+                                               |  *$'_MIGRATE' *$'_UNIQUE_KEY' *nm_4
+                                               |  *$'_MIGRATE' *$'_USER' *nm_2
+                                               |  *$'_MIGRATE' *$'_USERMESSAGE' *nm_n
+                                               |  *$'_MIGRATE' *$'_VIEW' *nm_3
+                                               |  *$'_MIGRATEDEPSONLY' *$'_DATABASE' *nm_1
+                                               |  *$'_MIGRATEDEPSONLY' *$'_FOREIGN_KEY' *nm_4
+                                               |  *$'_MIGRATEDEPSONLY' *$'_INDEX' *nm_4
+                                               |  *$'_MIGRATEDEPSONLY' *$'_PRIMARY_KEY' *nm_4
+                                               |  *$'_MIGRATEDEPSONLY' *$'_PROCEDURE' *nm_g
+                                               |  *$'_MIGRATEDEPSONLY' *$'_TABLE' *nm_3
+                                               |  *$'_MIGRATEDEPSONLY' *$'_TRIGGER' *nm_3
+                                               |  *$'_MIGRATEDEPSONLY' *$'_UNIQUE_KEY' *nm_4
+                                               |  *$'_MIGRATEDEPSONLY' *$'_USER' *nm_2
+                                               |  *$'_MIGRATEDEPSONLY' *$'_VIEW' *nm_3
+                                               |  *$'_REBUILD' *$'_INDEX' *nm_4
+                                               |  *$'_REBUILD' *$'_PRIMARY_KEY' *nm_4
+                                               |  *$'_REBUILD' *$'_PROCEDURE' *nm_g
+                                               |  *$'_REBUILD' *$'_TABLE' *nm_3
+                                               |  *$'_REBUILD' *$'_TRIGGER' *nm_3
+                                               |  *$'_REBUILD' *$'_UNIQUE_KEY' *nm_4
+                                               |  *$'_REBUILD' *$'_VIEW' *nm_3
+                                               |  *$'_RECOMPILE' *$'_TABLE' *nm_3
            db2_s                               =  *$'_ALTER' *$'_ALIAS' *nm_2 *db2_cmplx_changes
+                                               |  *$'_ALTER' *$'_CHECK' *nm_3 *db2_cmplx_changes
+                                               |  *$'_ALTER' *$'_DISTINCT_TYPE' *nm_2 *db2_cmplx_changes
+                                               |  *$'_ALTER' *$'_EVENT_MONITOR' *nm_1 *db2_cmplx_changes
+                                               |  *$'_ALTER' *$'_FOREIGN_KEY' *nm_3 *db2_cmplx_changes
+                                               |  *$'_ALTER' *$'_FUNCTION' *nm_3 *db2_cmplx_changes
+                                               |  *$'_ALTER' *$'_INDEX' *nm_2 *db2_cmplx_changes
+                                               |  *$'_ALTER' *$'_PACKAGE' *nm_2 *db2_cmplx_changes
+                                               |  *$'_ALTER' *$'_PRIMARY_KEY' *nm_3 *db2_cmplx_changes
+                                               |  *$'_ALTER' *$'_TABLE' *nm_2 *db2_cmplx_changes
+                                               |  *$'_ALTER' *$'_TABLESPACE' *nm_1 *db2_cmplx_changes
+                                               |  *$'_ALTER' *$'_SUMMARY_TABLE' *nm_2 *db2_cmplx_changes
+                                               |  *$'_ALTER' *$'_TRIGGER' *nm_2 *db2_cmplx_changes
+                                               |  *$'_ALTER' *$'_VIEW' *nm_2 *db2_cmplx_changes
+                                               |  *$'_ALTER' *$'_BUFFERPOOL' *nm_1 *db2_cmplx_changes
+                                               |  *$'_ALTER' *$'_NODEGROUP' *nm_1 *db2_cmplx_changes
+                                               |  *$'_ALTER' *$'_PROCEDURE' *nm_3 *db2_cmplx_changes
+                                               |  *$'_ALTER' *$'_SCHEMA' *nm_1 *db2_cmplx_changes
+                                               |  *$'_ALTER' *$'_UNIQUE_KEY' *nm_3 *db2_cmplx_changes
+                                               |  *$'_CREATE' *$'_ALIAS' *nm_2 *cmplx_attrs
+                                               |  *$'_CREATE' *$'_CHECK' *nm_3 *cmplx_attrs
+                                               |  *$'_CREATE' *$'_DISTINCT_TYPE' *nm_2 *cmplx_attrs
+                                               |  *$'_CREATE' *$'_EVENT_MONITOR' *nm_1 *cmplx_attrs
+                                               |  *$'_CREATE' *$'_FOREIGN_KEY' *nm_3 *cmplx_attrs
+                                               |  *$'_CREATE' *$'_FUNCTION' *nm_3 *cmplx_attrs
+                                               |  *$'_CREATE' *$'_INDEX' *nm_2 *cmplx_attrs
+                                               |  *$'_CREATE' *$'_PACKAGE' *nm_2 *cmplx_attrs
+                                               |  *$'_CREATE' *$'_PRIMARY_KEY' *nm_3 *cmplx_attrs
+                                               |  *$'_CREATE' *$'_SUMMARY_TABLE' *nm_2 *cmplx_attrs
+                                               |  *$'_CREATE' *$'_TABLE' *nm_2 *cmplx_attrs
+                                               |  *$'_CREATE' *$'_TABLESPACE' *nm_1 *cmplx_attrs
+                                               |  *$'_CREATE' *$'_TRIGGER' *nm_2 *cmplx_attrs
+                                               |  *$'_CREATE' *$'_VIEW' *nm_2 *cmplx_attrs
+                                               |  *$'_CREATE' *$'_BUFFERPOOL' *nm_1 *cmplx_attrs
+                                               |  *$'_CREATE' *$'_NODEGROUP' *nm_1 *cmplx_attrs
+                                               |  *$'_CREATE' *$'_PROCEDURE' *nm_3 *cmplx_attrs
+                                               |  *$'_CREATE' *$'_SCHEMA' *nm_1 *cmplx_attrs
+                                               |  *$'_CREATE' *$'_UNIQUE_KEY' *nm_3 *cmplx_attrs
+                                               |  *$'_DROP' *$'_ALIAS' *nm_2
+                                               |  *$'_DROP' *$'_CHECK' *nm_3
+                                               |  *$'_DROP' *$'_EVENT_MONITOR' *nm_1
+                                               |  *$'_DROP' *$'_FOREIGN_KEY' *nm_3
+                                               |  *$'_DROP' *$'_FUNCTION' *nm_3
+                                               |  *$'_DROP' *$'_INDEX' *nm_2
+                                               |  *$'_DROP' *$'_PACKAGE' *nm_2
+                                               |  *$'_DROP' *$'_PRIMARY_KEY' *nm_3
+                                               |  *$'_DROP' *$'_TABLE' *nm_2
+                                               |  *$'_DROP' *$'_TABLESPACE' *nm_1
+                                               |  *$'_DROP' *$'_SUMMARY_TABLE' *nm_2
+                                               |  *$'_DROP' *$'_TRIGGER' *nm_2
+                                               |  *$'_DROP' *$'_VIEW' *nm_2
+                                               |  *$'_DROP' *$'_BUFFERPOOL' *nm_1
+                                               |  *$'_DROP' *$'_NODEGROUP' *nm_1
+                                               |  *$'_DROP' *$'_PROCEDURE' *nm_3
+                                               |  *$'_DROP' *$'_SCHEMA' *nm_1
+                                               |  *$'_DROP' *$'_UNIQUE_KEY' *nm_3
+                                               |  *$'_MIGRATE' *$'_ALIAS' *nm_2
+                                               |  *$'_MIGRATE' *$'_CHECK' *nm_3
+                                               |  *$'_MIGRATE' *$'_DISTINCT_TYPE' *nm_2
+                                               |  *$'_MIGRATE' *$'_EVENT_MONITOR' *nm_1
+                                               |  *$'_MIGRATE' *$'_FOREIGN_KEY' *nm_3
+                                               |  *$'_MIGRATE' *$'_FUNCTION' *nm_3
+                                               |  *$'_MIGRATE' *$'_INDEX' *nm_2
+                                               |  *$'_MIGRATE' *$'_PRIMARY_KEY' *nm_3
+                                               |  *$'_MIGRATE' *$'_TABLE' *nm_2
+                                               |  *$'_MIGRATE' *$'_TABLESPACE' *nm_1
+                                               |  *$'_MIGRATE' *$'_SUMMARY_TABLE' *nm_2
+                                               |  *$'_MIGRATE' *$'_TRIGGER' *nm_2
+                                               |  *$'_MIGRATE' *$'_VIEW' *nm_2
+                                               |  *$'_MIGRATE' *$'_BUFFERPOOL' *nm_1
+                                               |  *$'_MIGRATE' *$'_NODEGROUP' *nm_1
+                                               |  *$'_MIGRATE' *$'_PROCEDURE' *nm_3
+                                               |  *$'_MIGRATE' *$'_SCHEMA' *nm_1
+                                               |  *$'_MIGRATE' *$'_UNIQUE_KEY' *nm_3
+                                               |  *$'_RECOMPILE' *$'_PACKAGE' *nm_2
+                                               |  *$'_REBUILD' *$'_ALIAS' *nm_2
+                                               |  *$'_REBUILD' *$'_CHECK' *nm_3
+                                               |  *$'_REBUILD' *$'_EVENT_MONITOR' *nm_1
+                                               |  *$'_REBUILD' *$'_FOREIGN_KEY' *nm_3
+                                               |  *$'_REBUILD' *$'_FUNCTION' *nm_3
+                                               |  *$'_REBUILD' *$'_INDEX' *nm_2
+                                               |  *$'_REBUILD' *$'_PRIMARY_KEY' *nm_3
+                                               |  *$'_REBUILD' *$'_TABLE' *nm_2
+                                               |  *$'_REBUILD' *$'_TABLESPACE' *nm_1
+                                               |  *$'_REBUILD' *$'_SUMMARY_TABLE' *nm_2
+                                               |  *$'_REBUILD' *$'_TRIGGER' *nm_2
+                                               |  *$'_REBUILD' *$'_VIEW' *nm_2
+                                               |  *$'_REBUILD' *$'_BUFFERPOOL' *nm_1
+                                               |  *$'_REBUILD' *$'_NODEGROUP' *nm_1
+                                               |  *$'_REBUILD' *$'_PROCEDURE' *nm_3
+                                               |  *$'_REBUILD' *$'_SCHEMA' *nm_1
+                                               |  *$'_REBUILD' *$'_UNIQUE_KEY' *nm_3
            mvs_s                               =  *mvs_alter_command
+                                               |  *mvs_create_command
+                                               |  *mvs_drop_command
                                                =  *mvs_alter_alias_1
            mvs_alter_alias_1                   =  *mvs_alter_alias_1 *mvs_alter_alias_1_1
            mvs_alter_alias_1_1                 =  *$'_OWNER' *MVS_STR
+                                               |  *$'_NAME' *MVS_STR
+                                               |  *$'_TABLE' *nm_2
+                                               |  *$'_TABLE' *nm_3
+                                               |  *$'_COMMENT' *$'_sq_string_'
+                                               |  *$'_NOCOMMENT'
+                                               |  *$'_LABEL' *$'_sq_string_'
+                                               |  *$'_NOLABEL'
                                                =  *mvs_alter_check_1
            mvs_alter_check_1                   =  *mvs_alter_check_1 *mvs_alter_check_1_1
            mvs_alter_check_1_1                 =  *$'_OWNER' *MVS_STR
+                                               |  *$'_NAME' *MVS_STR
+                                               |  *$'_CHECK' $'(' *error $')'
                                                =  *mvs_alter_database_1
            mvs_alter_database_1                =  *mvs_alter_database_1 *mvs_alter_database_1_1
            mvs_alter_database_1_1              =  *$'_NAME' *MVS_STR
+                                               |  *$'_OWNER' *MVS_STR
+                                               |  *$'_STOGROUP' *MVS_STR
+                                               |  *$'_STOGROUP' $'<' *$'_DEFLT' $'>'
+                                               |  *$'_BUFFERPOOL' *MVS_STR
+                                               |  *$'_BUFFERPOOL' $'<' *$'_DEFLT' $'>'
+                                               |  *$'_ROSHARE' *$'_OWNER'
+                                               |  *$'_ROSHARE' *$'_NONE'
+                                               |  *$'_ROSHARE' *$'_READ'
                                                =  *mvs_alter_foreign_key_1
            mvs_alter_foreign_key_1             =  *mvs_alter_foreign_key_1 *mvs_alter_foreign_key_1_1
            mvs_alter_foreign_key_1_1           =  *$'_NAME' *MVS_STR
+                                               |  *$'_REFERENCETB' *nm_2
+                                               |  *mvs_key_columns
+                                               |  *$'_ON' *$'_DELETE' *$'_CASCADE'
+                                               |  *$'_ON' *$'_DELETE' *$'_RESTRICT'
+                                               |  *$'_ON' *$'_DELETE' *$'_SET' *$'_NULL'
                                                =  *mvs_alter_index_1
            mvs_alter_index_1                   =  *mvs_alter_index_1 *mvs_alter_index_1_1
            mvs_alter_index_1_1                 =  *$'_OWNER' *MVS_STR
+                                               |  *$'_NAME' *MVS_STR
+                                               |  *$'_TABLE' *nm_2
+                                               |  *$'_UNIQUE' *MVS_STR
+                                               |  *$'_CLUSTER' *$'_YES'
+                                               |  *$'_CLUSTER' *$'_NO'
+                                               |  *$'_SUBPAGES' *num
+                                               |  *$'_NUMPARTS' *num
+                                               |  *$'_BUFFERPOOL' *MVS_STR
+                                               |  *$'_BUFFERPOOL' $'<' *$'_DEFLT' $'>'
+                                               |  *$'_CLOSE' *$'_YES'
+                                               |  *$'_CLOSE' *$'_NO'
+                                               |  *$'_ERASE' *$'_YES'
+                                               |  *$'_ERASE' *$'_NO'
+                                               |  *$'_DSETPASS' *MVS_STR
+                                               |  *$'_NODSETPASS'
+                                               |  *$'_ALTER' *error
+                                               |  *$'_ADD' *error
+                                               |  *$'_DROP' *error
+                                               |  *$'_PIECESIZE' *num *num_size
+                                               |  *mvs_key_columns
                                                =  *mvs_alter_stogroup_1
            mvs_alter_stogroup_1                =  *mvs_alter_stogroup_1 *mvs_alter_stogroup_1_1
            mvs_alter_stogroup_1_1              =  *$'_NAME' *MVS_STR
+                                               |  *$'_OWNER' *MVS_STR
+                                               |  *$'_VOLUMES' $'(' *error $')'
+                                               |  *$'_VCAT' *MVS_STR
+                                               |  *$'_VCATPASS' *MVS_STR
+                                               |  *$'_NOVCATPASS'
                                                =  *mvs_alter_synonym_1
            mvs_alter_synonym_1                 =  *mvs_alter_synonym_1 *mvs_alter_synonym_1_1
            mvs_alter_synonym_1_1               =  *$'_NAME' *MVS_STR
+                                               |  *$'_OWNER' *MVS_STR
+                                               |  *$'_TABLE' *nm_2
                                                =  *mvs_alter_table_1
            mvs_alter_table_1                   =  *mvs_alter_table_1 *mvs_alter_table_1_1
            mvs_alter_table_1_1                 =  *$'_OWNER' *MVS_STR
+                                               |  *$'_NAME' *MVS_STR
+                                               |  *$'_DATABASE' *MVS_STR
+                                               |  *$'_TABLESPACE' *MVS_STR
+                                               |  *$'_EDITPROC' *MVS_STR
+                                               |  *$'_NOEDITPROC'
+                                               |  *$'_VALIDPROC' *MVS_STR
+                                               |  *$'_NOVALIDPROC'
+                                               |  *$'_AUDIT' *$'_NONE'
+                                               |  *$'_AUDIT' *$'_CHANGES'
+                                               |  *$'_AUDIT' *$'_ALL'
+                                               |  *$'_ALTER' *error
+                                               |  *$'_ADD' *error
+                                               |  *$'_DROP' *error
+                                               |  *mvs_pkey_list
+                                               |  *$'_NOPRIMARYKEY'
+                                               |  *$'_COMMENT' *$'_sq_string_'
+                                               |  *$'_NOCOMMENT'
+                                               |  *$'_LABEL' *$'_sq_string_'
+                                               |  *$'_NOLABEL'
+                                               |  *$'_COLCOMMENT' *MVS_STR *$'_sq_string_'
+                                               |  *$'_NOCOLCOMMENT' *MVS_STR
+                                               |  *$'_COLLABEL' *MVS_STR *$'_sq_string_'
+                                               |  *$'_NOCOLLABEL' *MVS_STR
+                                               |  *$'_DATA' *$'_CAPTURE' *$'_CHANGES'
+                                               |  *$'_DATA' *$'_CAPTURE' *$'_NONE'
+                                               |  *$'_OBID' *num
                                                =  *mvs_alter_tablespace_1
            mvs_alter_tablespace_1              =  *mvs_alter_tablespace_1 *mvs_alter_tablespace_1_1
            mvs_alter_tablespace_1_1            =  *$'_DATABASE' *MVS_STR
+                                               |  *$'_NAME' *MVS_STR
+                                               |  *$'_OWNER' *MVS_STR
+                                               |  *$'_BUFFERPOOL' *MVS_STR
+                                               |  *$'_BUFFERPOOL' $'<' *$'_DEFLT' $'>'
+                                               |  *$'_LOCKSIZE' *$'_ANY'
+                                               |  *$'_LOCKSIZE' *$'_PAGE'
+                                               |  *$'_LOCKSIZE' *$'_TABLE'
+                                               |  *$'_LOCKSIZE' *$'_TABLESPACE'
+                                               |  *$'_LOCKSIZE' *$'_ROW'
+                                               |  *$'_LOCKMAX' *$'_SYSTEM'
+                                               |  *$'_LOCKMAX' *$'_ANY'
+                                               |  *$'_LOCKMAX' *num
+                                               |  *$'_CLOSE' *$'_YES'
+                                               |  *$'_CLOSE' *$'_NO'
+                                               |  *$'_DSETPASS' *MVS_STR
+                                               |  *$'_NODSETPASS'
+                                               |  *$'_SEGSIZE' *num
+                                               |  *$'_NUMPARTS' *num
+                                               |  *$'_ERASE' *$'_YES'
+                                               |  *$'_ERASE' *$'_NO'
+                                               |  *$'_ALTER' *error
+                                               |  *$'_ADD' *error
+                                               |  *$'_DROP' *error
                                                =  *mvs_alter_view_1
            mvs_alter_view_1                    =  *mvs_alter_view_1 *mvs_alter_view_1_1
            mvs_alter_view_1_1                  =  *$'_QUALIFIED' *$'_YES'
+                                               |  *$'_QUALIFIED' *$'_NO'
+                                               |  *$'_QUALIFIER' *$'_YES'
+                                               |  *$'_QUALIFIER' *$'_NO'
+                                               |  *$'_OWNER' *MVS_STR
+                                               |  *$'_NAME' *MVS_STR
+                                               |  *$'_CHECK' *$'_OPTION' *$'_YES'
+                                               |  *$'_CHECK' *$'_OPTION' *$'_NO'
+                                               |  *$'_COMMENT' *$'_sq_string_'
+                                               |  *$'_NOCOMMENT'
+                                               |  *$'_LABEL' *$'_sq_string_'
+                                               |  *$'_NOLABEL'
+                                               |  *$'_COLCOMMENT' *MVS_STR *$'_sq_string_'
+                                               |  *$'_NOCOLCOMMENT' *MVS_STR
+                                               |  *$'_COLLABEL' *MVS_STR *$'_sq_string_'
+                                               |  *$'_NOCOLLABEL' *MVS_STR
+                                               |  *$'_COLUMNS' $'(' *mvs_constant_list $')'
+                                               |  *$'_NOCOLUMNS'
+                                               |  *$'_ALTER' *error
+                                               |  *$'_ADD' *error
+                                               |  *$'_DROP' *error
+                                               |  *mvs_sub_select
                                                =  *mvs_create_alias_1
            mvs_create_alias_1                  =  *mvs_create_alias_1 *mvs_create_alias_1_1
            mvs_create_alias_1_1                =  *$'_TABLE' *nm_2
+                                               |  *$'_TABLE' *nm_3
+                                               |  *$'_COMMENT' *$'_sq_string_'
+                                               |  *$'_LABEL' *$'_sq_string_'
            mvs_create_command                  =  *$'_CREATE' *$'_CHECK' *mvs_create_check_1 *mvs_create_check_2
            mvs_create_check_1                  =  *nm_2
                                                =  *mvs_create_check_2
            mvs_create_check_2                  =  *mvs_create_check_2 *mvs_create_check_2_1
            mvs_create_check_2_1                =  *$'_CHECK' $'(' *condition $')'
                                                =  *mvs_create_database_1
            mvs_create_database_1               =  *mvs_create_database_1 *mvs_create_database_1_1
            mvs_create_database_1_1             =  *$'_OWNER' *id
+                                               |  *$'_STOGROUP' *id
+                                               |  *$'_STOGROUP' $'<' *$'_DEFLT' $'>'
+                                               |  *$'_BUFFERPOOL' *id
+                                               |  *$'_BUFFERPOOL' $'<' *$'_DEFLT' $'>'
+                                               |  *$'_ROSHARE' *$'_READ'
+                                               |  *$'_ROSHARE' *$'_OWNER'
+                                               |  *$'_ROSHARE' *$'_NONE'
            mvs_create_command                  =  *$'_CREATE'
+                                                  *$'_FOREIGN'
+                                                  *$'_KEY'
+                                                  *mvs_create_fkey_1
+                                                  *mvs_create_fkey_2
            mvs_create_fkey_1                   =  *nm_2
                                                =  *mvs_create_fkey_2
            mvs_create_fkey_2                   =  *mvs_create_fkey_2 *mvs_create_fkey_2_1
            mvs_create_fkey_2_1                 =  *$'_REFERENCETB' *nm_2
+                                               |  *mvs_key_columns
+                                               |  *mvs_ref_columns
+                                               |  *$'_ON' *$'_DELETE' *$'_CASCADE'
+                                               |  *$'_ON' *$'_DELETE' *$'_RESTRICT'
+                                               |  *$'_ON' *$'_DELETE' *$'_SET' *$'_NULL'
+                                               |  *$'_ON' *$'_DELETE' *$'_NO' *$'_ACTION'
                                                =  *mvs_create_index_1
            mvs_create_index_1                  =  *mvs_create_index_1 *mvs_create_index_1_1
            mvs_create_index_1_1                =  *$'_TABLE' *nm_2
+                                               |  *mvs_key_columns
+                                               |  *$'_UNIQUE' *MVS_STR
+                                               |  *$'_CLUSTER' *$'_YES'
+                                               |  *$'_CLUSTER' *$'_NO'
+                                               |  *$'_SUBPAGES' *num
+                                               |  *$'_TYPE' *num
+                                               |  *$'_BUFFERPOOL' *MVS_STR
+                                               |  *$'_BUFFERPOOL' $'<' *$'_DEFLT' $'>'
+                                               |  *$'_CLOSE' *$'_YES'
+                                               |  *$'_CLOSE' *$'_NO'
+                                               |  *$'_ERASE' *$'_YES'
+                                               |  *$'_ERASE' *$'_NO'
+                                               |  *$'_DSETPASS' *MVS_STR
+                                               |  *$'_PIECESIZE' *num *num_size
+                                               |  *$'_PART' *num *mvs_index_part_parms
+                                               |  *$'_PARTS' *num *mvs_index_part_parms
+                                               |  *$'_NUMPARTS' *num *mvs_index_part_parms
                                                =  *mvs_create_stogroup_1
            mvs_create_stogroup_1               =  *mvs_create_stogroup_1 *mvs_create_stogroup_1_1
            mvs_create_stogroup_1_1             =  *$'_VCAT' *id
+                                               |  *$'_VCAT' *id *$'_VCATPASS' *MVS_STR
+                                               |  *$'_VOLUMES' $'(' *error $')'
+                                               |  *$'_OWNER' *id
            mvs_create_command                  =  *$'_CREATE' *$'_SYNONYM' *nm_2 *$'_TABLE' *nm_2
                                                =  *mvs_create_table_1
            mvs_create_table_1                  =  *mvs_create_table_1 *mvs_create_table_1_1
            mvs_create_table_1_1                =  *mvs_create_table_columns
+                                               |  *$'_DATABASE' *MVS_STR
+                                               |  *$'_TABLESPACE' *MVS_STR
+                                               |  *$'_TABLESPACE' $'<' *$'_DEFLT' $'>'
+                                               |  *$'_TYPE' *MVS_STR
+                                               |  *$'_EDITPROC' *MVS_STR
+                                               |  *$'_VALIDPROC' *MVS_STR
+                                               |  *$'_AUDIT' *$'_NONE'
+                                               |  *$'_AUDIT' *$'_CHANGES'
+                                               |  *$'_AUDIT' *$'_ALL'
+                                               |  *$'_CCSID' *$'_ASCII'
+                                               |  *$'_CCSID' *$'_EBCDIC'
+                                               |  *mvs_pkey_list
+                                               |  *$'_COMMENT' *$'_sq_string_'
+                                               |  *$'_LABEL' *$'_sq_string_'
+                                               |  *$'_COLCOMMENT' *MVS_STR *$'_sq_string_'
+                                               |  *$'_COLLABEL' *MVS_STR *$'_sq_string_'
+                                               |  *$'_DATA' *$'_CAPTURE' *$'_CHANGES'
+                                               |  *$'_DATA' *$'_CAPTURE' *$'_NONE'
+                                               |  *$'_OBID' *num
+                                               |  *$'_DROPRESTRICT' *$'_YES'
+                                               |  *$'_DROPRESTRICT' *$'_NO'
            mvs_create_table_columns            =  *$'_COLUMNS' $'(' *mvs_column_definitions $')'
            mvs_column_definition               =  *MVS_STR *mvs_column_datatype *mvs_column_definition_1
            mvs_column_definitions              =  *mvs_column_definition
                                                =  *mvs_column_definition_1
            mvs_column_definition_1             =  *mvs_column_definition_1 *mvs_column_definition_1_1
            mvs_column_definition_1_1           =  *$'_FOR' *$'_BIT' *$'_DATA'
+                                               |  *$'_FOR' *$'_SBCS' *$'_DATA'
+                                               |  *$'_FOR' *$'_MIXED' *$'_DATA'
+                                               |  *$'_FIELDPROC' *MVS_STR
+                                               |  *$'_FIELDPROC' *MVS_STR $'(' *mvs_string_list $')'
+                                               |  *$'_NOT' *$'_NULL'
+                                               |  *$'_NOT' *$'_NULL' *$'_WITH' *$'_DEFAULT'
+                                               |  *$'_DEFAULTVALUE' *$'_sq_string_'
+                                               |  *$'_DEFAULTVALUE' *$'_X' *$'_sq_string_'
+                                               |  *$'_DEFAULTVALUE' *$'_N' *$'_sq_string_'
+                                               |  *$'_DEFAULTVALUE' *$'_G' *$'_sq_string_'
+                                               |  *$'_DEFAULTVALUE' *$'_dq_string_'
+                                               |  *$'_DEFAULTVALUE' *$'_X' *$'_dq_string_'
+                                               |  *$'_DEFAULTVALUE' *$'_N' *$'_dq_string_'
+                                               |  *$'_DEFAULTVALUE' *$'_G' *$'_dq_string_'
+                                               |  *$'_DEFAULTVALUE' *num
+                                               |  *$'_DEFAULTVALUE' *$'_USER'
+                                               |  *$'_DEFAULTVALUE' *$'_CURRENT' *$'_SQLID'
+                                               |  *$'_NULL'
+                                               |  *$'_NULL' *$'_DEFAULT'
            mvs_column_datatype                 =  *$'_CHAR' $'(' *num $')'
+                                               |  *$'_VARCHAR' $'(' *num $')'
+                                               |  *$'_LONG' *$'_VARCHAR' $'(' *num $')'
+                                               |  *$'_LONG' *$'_VARCHAR'
+                                               |  *$'_INTEGER'
+                                               |  *$'_SMALLINT'
+                                               |  *$'_FLOAT' $'(' *num $')'
+                                               |  *$'_DECIMAL' $'(' *num $')'
+                                               |  *$'_DECIMAL' $'(' *num $',' *num $')'
+                                               |  *$'_GRAPHIC' $'(' *num $')'
+                                               |  *$'_VARGRAPHIC' $'(' *num $')'
+                                               |  *$'_LONG' *$'_VARGRAPHIC'
+                                               |  *$'_DATE'
+                                               |  *$'_TIME'
+                                               |  *$'_TIMESTAMP'
                                                =  *mvs_create_tablespace_1
            mvs_create_tablespace_1             =  *mvs_create_tablespace_1 *mvs_create_tablespace_1_1
            mvs_create_tablespace_1_1           =  *mvs_create_tablespace_1_2 *$'_PART' *num *mvs_tablespace_parts
+                                               |  *mvs_create_tablespace_1_2 *$'_PARTS' *num *mvs_tablespace_parts
+                                               |  *$'_OWNER' *MVS_STR
+                                               |  *$'_BUFFERPOOL' *MVS_STR
+                                               |  *$'_BUFFERPOOL' $'<' *$'_DEFLT' $'>'
+                                               |  *$'_LOCKSIZE' *$'_ANY'
+                                               |  *$'_LOCKSIZE' *$'_PAGE'
+                                               |  *$'_LOCKSIZE' *$'_TABLE'
+                                               |  *$'_LOCKSIZE' *$'_TABLESPACE'
+                                               |  *$'_LOCKSIZE' *$'_ROW'
+                                               |  *$'_LOCKMAX' *$'_SYSTEM'
+                                               |  *$'_LOCKMAX' *$'_ANY'
+                                               |  *$'_LOCKMAX' *num
+                                               |  *$'_CLOSE' *$'_YES'
+                                               |  *$'_CLOSE' *$'_NO'
+                                               |  *$'_DSETPASS' *MVS_STR
+                                               |  *$'_SEGSIZE' *num
+                                               |  *$'_ERASE' *$'_YES'
                                                =  *mvs_create_tablespace_1_2
            mvs_create_tablespace_1_2           =  *$'_NUMPARTS' *num
            mvs_tablespace_parts                =  *mvs_index_part_parms
            mvs_create_command                  =  *$'_CREATE' *$'_VIEW' *mvs_create_view_0 *mvs_create_view_1
            mvs_create_view_0                   =  *id
                                                =  *mvs_create_view_1
            mvs_create_view_1                   =  *mvs_create_view_1 *mvs_create_view_1_1
            mvs_create_view_1_1                 =  *$'_QUALIFIED' *$'_YES'
+                                               |  *$'_QUALIFIED' *$'_NO'
+                                               |  *$'_QUALIFIER' *$'_YES'
+                                               |  *$'_QUALIFIER' *$'_NO'
+                                               |  *$'_COLUMNS' $'(' *mvs_constant_list $')'
+                                               |  *$'_COMMENT' *$'_sq_string_'
+                                               |  *$'_LABEL' *$'_sq_string_'
+                                               |  *mvs_sub_select
+                                               |  *$'_COLLABEL' *MVS_STR *$'_sq_string_'
+                                               |  *$'_COLCOMMENT' *MVS_STR *$'_sq_string_'
+                                               |  *$'_CHECK' *$'_OPTION' *$'_YES'
+                                               |  *$'_CHECK' *$'_OPTION' *$'_NO'
+                                               |  *$'_CHECK' *$'_OPTION' *$'_LOCAL'
            mvs_drop_command                    =  *$'_DROP' *$'_ALIAS' *nm_2
+                                               |  *$'_DROP' *$'_CHECK' *nm_3
+                                               |  *$'_DROP' *$'_DATABASE' *id
                                                =  *mvs_drop_fkey_1
            mvs_drop_fkey_1                     =  *mvs_drop_fkey_1 *mvs_drop_fkey_1_1
            mvs_drop_fkey_1_1                   =  *$'_REFERENCETB' *nm_2
+                                               |  *mvs_key_columns
            mvs_drop_command                    =  *$'_DROP' *$'_INDEX' *nm_2
+                                               |  *$'_DROP' *$'_STOGROUP' *id
+                                               |  *$'_DROP' *$'_SYNONYM' *nm_2
+                                               |  *$'_DROP' *$'_TABLE' *nm_2
+                                               |  *$'_DROP' *$'_TABLESPACE' *nm_2
+                                               |  *$'_DROP' *$'_VIEW' *nm_2
            mvs_attr_1                          =  *MVS_STR
+                                               |  *MVS_STR *$'_ASC'
+                                               |  *MVS_STR *$'_DESC'
            mvs_attrs_1                         =  *mvs_attr_1
+                                               |  *mvs_attrs_1 $',' *mvs_attr_1
            mvs_key_columns                     =  *$'_KEYCOLUMNS' $'(' *mvs_attrs_1 $')'
            mvs_ref_columns                     =  *$'_REFCOLUMNS' $'(' *mvs_attrs_1 $')'
            mvs_pkey_list                       =  *$'_PRIMARYKEY' $'(' *mvs_attrs_1 $')'
            mvs_constant_list                   =  *mvs_string
                                                =  *mvs_index_part_parms
            mvs_index_part_parms                =  *mvs_index_part_parms *mvs_index_part_parms_1
            mvs_index_part_parms_1              =  *$'_VCAT' *MVS_STR
+                                               |  *$'_STOGROUP' *MVS_STR *mvs_index_part_parms_2
+                                               |  *$'_STOGROUP' $'<' *$'_DEFLT' $'>' *mvs_index_part_parms_2
+                                               |  *$'_VALUES' $'(' *mvs_index_part_parms_1_1 $')'
+                                               |  *$'_PCTFREE' *num
+                                               |  *$'_FREEPAGE' *num
+                                               |  *$'_COMPRESS' *$'_YES'
+                                               |  *$'_COMPRESS' *$'_NO'
            mvs_index_part_parms_1_1            =  *mvs_string
                                                =  *mvs_index_part_parms_2
            mvs_index_part_parms_2              =  *mvs_index_part_parms_2 *mvs_index_part_parms_2_1
            mvs_index_part_parms_2_1            =  *$'_PRIQTY' *num
                                                =  *num_size
            num_size                            =  *$'_K'
+                                               |  *$'_G'
+                                               |  *$'_M'
            as                                  =  *$'_AS'
            mvs_sub_select                      =  *as *query
